apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secret
  namespace: observability
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:6tUohR/86teyjo9l7h3KrtgcPu2xABcPC4zRo1+EFkI7k4+1AuSoVg==,iv:7iiRbiHSA7MvPtNHCv4lnckQRmnCBsZqO8WhMhZLE+A=,tag:NCIWTpdeICZ7+aPYjivQaw==,type:str]
  client_secret: ENC[AES256_GCM,data:h3DXOzO5dARa5Bp+h0pAaeJUTiigTusTfJUA7x+BIumrb9atkkrkJgWi/CcH3R1vWi8EEUG6GHINhK6Ove6SjPGiLDP7jgap/yR/2zkpLf5tQ1r5YSQfJcYioodLbBo6XRl6164iMiBHTDrAWLQMx7/Fq/fuoTBoGpoFxmxKkfU=,iv:1qCspL8X5UK6J3fTOvLpgG/PtyCoy2zT4aue+k/LrP0=,tag:PjGVkwaBCXq5VfxFp4Sgiw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTEJOMzVCWXRESWVPZUdT
        WVp1NXZ1YTRrVG9GbHNwekRJMytIcEVReGtVCjhjWDNFTkVmd0lsSG1ObERqRUtm
        MEpJYzgxYWdaVzF6VXJkM0JKQ3R4dmcKLS0tIDRINnAwUUVmallqRFN5OEdNcmVR
        ajQrMjFlZTRjZjg0SlBOTHFqb2Fwb28K4hPixfF5ooXJMeyvc6RxV5an+v2VMB2N
        J6nZLOYFgdWd6aq1LDGwFgk+dioIRjBOWj1KXnlFeZ6x7cr65tLxtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T18:49:05Z"
  mac: ENC[AES256_GCM,data:r0HM4NgLrGFynORm7v7VK82tdUy253LS8PBEKPQc+e6tJEIl+KarHH3Wve8/fFiIr2XDkngI2Kwfx8Cun4vgKAQ+NsI2eA0MjPY29dj7JI8zK1fhggkPd1vuKSsZIOLceIFszHaV6y3qPGmRc3ss74yKlU9BZK6YoBC/oOLkcUg=,iv:G8C7glWM8RyJRAEvXxGJXlz0tGqnIc00PErofvmmJfw=,tag:/H5TXUklts72SzMPGHzd/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
