apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-secrets
type: Opaque
stringData:
  cookie-secret: ENC[AES256_GCM,data:e1EAd9E8sV/5CgI534rbfUib/2TWW2y+CfeLbdWY+hmgMayaO4nF7RJYNC2AqgMvda6lYcGhL23pHh6klT57hQ==,iv:a5Ur0r1YxkDV2rB9z6iAz5SYFVHNDbUevoiWx+2a5wo=,tag:Ffgl64sq0RhO2tzI1jEZ8w==,type:str]
  proxy-token: ENC[AES256_GCM,data:OlQZ+16Dnl3jDM4g5vdp0fJuxIEdb4k6RbtDOTDYq1Fwcn4e7VaPhLLmnLUBrBWCJmovvVU//atwpQafcQ3e4g==,iv:Zp598rqIt4V+SseKsRjmCUWHS/cNFN4OcUFVjFCOqBU=,tag:mRLVziYfSWkgEbzZNhUarQ==,type:str]
  client-id: ENC[AES256_GCM,data:1VfNsjGk10CVhg5IwXGmNk9WCgglrC8Fj8lOWxgOz1uGNbqo3laHCA==,iv:a44MRum3PoKm3bSkck4o2V9hMc2sA/bD1M2W3/DT1rc=,tag:OeRz/18LwcbKRF4A2Qrn7w==,type:str]
  client-secret: ENC[AES256_GCM,data:ytDQAPCVCiVabpUXE47sqoSVvkO2uQq/WuuZBzyDH5mbldHp9Z+uwujO8G8=,iv:SfztSSkM1AOQ6++5/ONbELG8Q6/IvUUbVmRg1WT0PY8=,tag:HQDnAX7iWYvuIGkMQaMkug==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NW9wZ3lnS2NkYW5FRXF4
        ektQaXVVTWtNZFNOK2p5cVJHRUxxcmR5UURRCmRXd2lLTzYzZHh2R0R5Q2JxZFNT
        Qm1UWFdERHR5cmduY1diUzRydTFrREUKLS0tIGVTTG84amJadXhkVUVGamx0bnVl
        bFRPcnZYMkFCYnVEWmVBRmd2MFdSejAKgnc0D6leHEDMcAY2u/eiN//W+V4f66wp
        CEglHZMY1ByoaopgtCe5j8kNrWpQr9IQ90jQzElJ7rNRuvG9PXkAtQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-26T15:20:49Z"
  mac: ENC[AES256_GCM,data:TQCCMy87Av/HvDAKOiWpreQZLU86Ltri2bp9X83PYL5Emwx9Zjh93wGMvD9mBuu3zfAXy+5B9MdI3tscoh/SkA+bYbrbzhAqpWTRDRhm1rcxbe2wa3Ai1AjRgX5myb7lePU0Jk/BKtEywSFL26rsHwkLtPWgOwISsVvI6bMBSJ4=,iv:LHb3ZYqyStqYPzi7rdq3YCx434Un2pe6Blp9qLCfElc=,tag:KNmlHh7xmnIlID8PAWF84g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
