---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-production-v1
  resources:
    requests:
      storage: 10Gi
