apiVersion: v1
kind: Secret
metadata:
  name: glpi-mariadb-auth
  namespace: default
type: Opaque
stringData:
  mariadb-root-password: ENC[AES256_GCM,data:6Puus6gnYQy9VwUEqtqqvScodG8o09HRoGyTHgLnpjvVM89ft2fioSbfsA==,iv:E2fTi68J+zXqUxxLYb73sOIzea6VXj8dwl6AbgvxaRY=,tag:Uylswhp5vVKqWdl1n9ZwYg==,type:str]
  mariadb-user-password: ENC[AES256_GCM,data:+67BJMjB7DRRUawUTgAvzDdRYC1fxwII7WPiT3Af0Xsaxl6h4Ovu5JkNAg==,iv:JGpbhOWzbfGuug4tEVCshMQg7v3rlI0KI6qpfFIMvAk=,tag:sW40HFh4nPCgQGQ1W4MI3Q==,type:str]
  mariadb-replication-password: ENC[AES256_GCM,data:Oat2fS3+R2/AuN+E8L4qN5e0WrA5Krci9/+F3+rlg6iwPCBzKEJ+XnQj4w==,iv:OMy1KFgNhY6CRMLcqghS5D5JOoGALEcVnoAd/okIQZI=,tag:mRb4uLz5OweoXW2PmmHgiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdHB3RHFGUVZUSTA3ZXpB
        RlAwdTB1ZUNhTEx2d3FMY1lqV0JoT2tUczJJCmtZdk9jYXRCdjVYQ2RxTkJ6akVJ
        UWZVRUNtWUJubVVuVzcvUTh2MFc4RzgKLS0tIDV1WVkzK2VKWk9EbXNabm9xRGxL
        OHNlMmptdXB4MkpNblJ3cldDTUxQa0EK7JVQ3VE0RM5D7gF1R09JqQ0j4LT8bzWa
        OuyTJwmU/SgNnxk1301Xk8fdO3K7WbkrbHxLyMXBik6ou7zQVEIJkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T16:23:57Z"
  mac: ENC[AES256_GCM,data:rSXSQiRt7kFihWrOyOLMkDlIV93pxSuC3OFNj77h2OIadcBqy42ocBkFeXTfflPa+Py78O7p3UWhg5mzskmnWpWc/F0IGmOG53emZqkJFKFPGg1FSSs4uaTSsyIbASchXeTxVYjR4NCVrmKJ256TNto53of3bv0jAiNAqh9Qfeo=,iv:gSlC1TItIzsF/E+GgDjqmMAq/+/Yv4bSsDJBN/KbAhY=,tag:FrdjfAWoan2sMg3SnTMxAw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
