# TODO: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-metrics
  namespace: observability
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:NgursfxFSw==,iv:SnKsLXFbmxO+Jl4SzduDKwKs12enWsgm/svwHfT8OSY=,tag:0C77vilmpqEqXisJHj2EMg==,type:str]
  password: ENC[AES256_GCM,data:SpEWFdCh4YjiPMrmpN85k+0iQsEEEjiAjLHl4ziG9uZIoWc6bAFTVGdzglo=,iv:iXXfcxP9uYflRy4VPhYsQlEjo6/v4OQCYk093idvs5g=,tag:lI7Rj9rstyteQ0gcppVxkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbGFDSEVQeEkxdk9HY3ZR
        N3UzcXh2aVhYY2RtM2liVUU3c1prNFI5a21BClZ1TDVwNTJ5TzgxelM1ZDU1Ymx3
        UU5zQ0FIdGZmU05jL0IxelFjUHFFcHcKLS0tIGVFZXBpQ0hLdVFyTHdSYUdHckFj
        R3dFZC84ZHNpNG1nQ210QndvOGhLUkEKOBW11x0VmGtlhmHulZr+QFcSBJvMiUQD
        V9dh5Sg+0Fz6QGix6E3Nk8LJmJ4UIooI1nqPhqXe1meMNdYcJdnU/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T08:23:44Z"
  mac: ENC[AES256_GCM,data:Ytuli1tPsMmsNzOUw3BVWYnPY7qzH8La95ZBCWVI6s4cg3i4wZsd/2hVCusEMN+DNu8k9v7rQ2bgXpE6IzLSxDAEb7F6/0ULquIUQ+TBsnSex4annl5rf43nUq/vLy3BtRoZ6spIDF/h1mmjszXjU+LQ8YMT7BAw5E50ci+IKeM=,iv:G0BNrllrHx8V4ziJwH+23LadYSB9GGQ8UrIobIL5egQ=,tag:EPP5sxPaHqW4Q4ZlTEOn+A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
