---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# Prowlarr — trafic HTTP/HTTPS routé via le proxy gluetun du vpn-stack.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
spec:
  chart:
    spec:
      chart: app-template
      version: '3.7.3'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media-server
  releaseName: prowlarr
  interval: 1h
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/prowlarr
              tag: 2.5.2
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "Europe/Paris"
              HTTP_PROXY: "http://vpn-stack.media-server.svc.cluster.local:8888"
              HTTPS_PROXY: "http://vpn-stack.media-server.svc.cluster.local:8888"
              NO_PROXY: "10.0.0.0/8,192.168.0.0/16,media-server.svc.cluster.local"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      main:
        controller: main
        ports:
          http:
            port: 9696

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn-production-v1
        accessMode: ReadWriteOnce
        size: 256Mi
        globalMounts:
          - path: /config
