---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
spec:
  chartRef:
    kind: OCIRepository
    name: netbox
  interval: 1h
  timeout: 20m # default 5min is too short for update
  values:
    timezone: 'Europe\Paris'
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
        ephemeral-storage: 50Mi
      limits:
        cpu: 750m
        memory: 1536Mi
        ephemeral-storage: 2Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    superuser:
      existingSecret: netbox-superuser
    valkey:
      enabled: true
      replica:
        replicaCount: 0
    persistence:
      enabled: true
