apiVersion: v1
kind: Secret
metadata:
  name: netbox-oidc
  namespace: default
type: Opaque
stringData:
  extra-oidc.yaml: ENC[AES256_GCM,data:g5XZJnKZX1xduRq4FG6zCytVC1ugZycSEPs0RbzYo+OX91Q1zU71aOqx37OMEYe5Ogn3IJp8F2nn3IV7FqDJVlOiPc2MDw1oUdPdcZCPmhAtK8f+SrjdpEzK,iv:YAoAMhAOg5d0xxC3501AdKMpigfbkNM/R4uWbnsY9bA=,tag:4OPpHqzFKiNYpJsY61dKSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dm5XaEI2UURNN1R1dWEv
        T2c1K21pZGNDTUdmOWczajQ2L2NBMVV6Q3hrCktoL2JnVXZaT2RFclBMU3JvdDFa
        YjdwMityTmREZTI2Zm5aN09tb0VGZW8KLS0tIGRZS1Q2R0dPdTVPVDYwN25oR3JD
        WUl4eVRlNVpnL2NWd3RKVVlibkZBdzgKy7eCWSM9qnR7TXCQwAJLyJjB68zCBbLW
        kMsVkaWKuJGAT4Foyu+iz3G6oOSy1PoYl13dn6W71L5Cg85SRUxeDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:23:17Z"
  mac: ENC[AES256_GCM,data:KsXl4buG0wdvQJvn+QzVqslBkEK6D5PktHJ+SxoSG7RtwJ71zJdreg92mezbmNE1Cai78r3vaxeq9cs1QDRrmXRXmC/YEkd89bWSMhueKsiW7GGXsoXJQsFYC6ujtiEFsGM4+R2f4XUvghZ96O4PNc5glf7ZIkKRy2IKUKD7W+8=,iv:onmvEKe8bu+k67s2y5VHWoqXj5gaFykqd/njF6lKc6M=,tag:xVQmgof+bLG9SObUyLojpg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
