# Dead man's switch ping URL, hosted outside the cluster on purpose. The
# embedded token is why this is encrypted: it could fake a live cluster.
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-heartbeat
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:Xrs+CqZHnwHRwO010bTgIsbFpKOhxiZxSSkNu9aP7VwZktZ15Lnm1YM48NYYb29AFt/jGiBKz/E=,iv:bXKyh2nc7dGvXZvBl8aOLTUfjP5xWbpGxrRQJkUaiVI=,tag:k2Ep/xImdkYm5OgEeYsZGQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTU1aZDkvMGsxaFFtcnM0
        VTRraytZQUtnZ0tJdXpzS3dsZGFqb0VveEJvClliZWJqdjkvd1g4VnVheWJtWmF1
        VytIWE5kcytmUEFTRzRKK0RLdGlYMjAKLS0tIFRZcThSdFFDcVhXUW1USm9qbmJa
        OGNROVl3R0VzZHZjdWZIRDZrWUs1dnMKEGCUXuzi/kA8AN22CMUf1cCYG+F0q2Df
        5uU0kyKVq1Mie9cO+zEWdFs4aHpC+p1P+enEWV8BX/e1hpYXqnXWPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T13:08:38Z"
  mac: ENC[AES256_GCM,data:pXY4ruvUOENcg0x2oekgrRNV2FwEdXVuesqjswdLbsvzy7DziLSzX5SM2VeBl/9Hfzl/rufvpqN8vHW4KgwmW7YOQ1pI+XQrClCdb6q404D4kATp/1VHBdk+cYojZMIDeiqTUlq6CZo9ZUB8sJs+R6zYUZDLrzL5qXBUh/w1wqI=,iv:hMiR+Y2BH0Ycux5i25SRe8tznWXjd0i/3+Xin+hYv20=,tag:RdRew/7aiugGvjsoyUJPqQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
