apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:3hFv7XNGbzZBr3Bm7AgoX6yprs2QzO63APAfuqxsjcZTAcgEm7zDO6Yj16534WQwDJ+DvB8RLgaEeT9VMObcPBFtKmDNoulSYAYo3+cHFSzsY+ACFPGmiqbvZwMvT7VWfb7yNZ6eUlGGBCxmvUoZN0uefiTZax2Wow==,iv:ZQyd5DL3loni3n7J9l/R1EBWhSbnLXnbu6Ly/RR8VIU=,tag:vjil4r+RQZVMJFIbyacKlA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R3NaNDBMSTJoNXkwM0t5
        VURabFMxdFFEa3FMbHUrYmdlUWdydFJYYzNNCms0M1RyazdvdkdGbDRsQmY4eDhM
        QkZBMXNZVUlkM0xBc0Jwc21Bc2J4eXcKLS0tIHN1U2JTd0Ivem1OWXYrTnVXVnZ0
        UStEbEI2ejNyUU1mVmEyWWtMeFR5emsKX0TJ4upLX03KcGXxKOtoY3CNdvlvf9VC
        K8sa7a+qNrH9jGro1gIgviyCSHzizpHkI3zWR0CQyj9T2yLkaQVXIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T12:50:19Z"
  mac: ENC[AES256_GCM,data:eOCOi/DuAQk+isBirBupN/IvmkaNVw+wsLsgqgIlzFCfdnVlvzziaD3UxP9vzhKsv+F2Gwb100Ubz+y4HjRzTfBP+nlFbJIPnHFR4qZ9jHaQbSYDXJEyGUB4qwnm9iCSViZw7wjTkEAvZD4aEI6rY2JOf8er50ltQb++crZ9wnw=,iv:EdmkMGq/X/jUh7aonvVI7pUzmcedX4Qh4cOK5sf3M8I=,tag:12zZBhLAv6mPDn+loQ1BdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
