apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:U9b8rJxQtkUe0ATO7w5vUduDM2xhIFav6CJX7EUOXsHURGs6+tzdJqVzVheI5IqqyXm2wfEM/2NKxhuXcnfmRVS/o2l1j15Gqn3belGMOW8/x3oaMm/n+aQh+VLUnAowcT11MtufhFy9NuN0DTBwE5JZ+JPrG8L36w==,iv:BoaRGV/TX7WZx5i33AufnvBMFXWuTSa2qab2uY6J4cQ=,tag:17z0q32wQLfg+Ip2/KTf+g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R3NaNDBMSTJoNXkwM0t5
        VURabFMxdFFEa3FMbHUrYmdlUWdydFJYYzNNCms0M1RyazdvdkdGbDRsQmY4eDhM
        QkZBMXNZVUlkM0xBc0Jwc21Bc2J4eXcKLS0tIHN1U2JTd0Ivem1OWXYrTnVXVnZ0
        UStEbEI2ejNyUU1mVmEyWWtMeFR5emsKX0TJ4upLX03KcGXxKOtoY3CNdvlvf9VC
        K8sa7a+qNrH9jGro1gIgviyCSHzizpHkI3zWR0CQyj9T2yLkaQVXIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T08:31:04Z"
  mac: ENC[AES256_GCM,data:jnbTWboTS85lg7vKnSSzQrPeMwFL5lUXlqSmAEFHUAa9rwlPOSlqQkRqAJUoYjjFJanSzHTWkZPYIS9beuIc+9/V6bkCLKzhQ8amtJpYqrbdGVZU7to0JLhIVBWnOQJJz2ks5/ToWSw6F6JcbGWhUomM5vFrK03t1zECzp7eDUw=,iv:OwFqvFiZl+T8IM/qw55jam0r4qS/dKG55x3n9ZCEKMY=,tag:ejj7TS+/megT2MZp2+013w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
