apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:K6t4e8KOjZ1qtU2A0dk3PH2FXP0sZFQ8ZsFYVF3/W3l8DvJuxk1G5bXEXqBBLOy83advq+dWuNEjkEOBxvlMtw==,iv:FdAszm/lQCRHSnh61m/8eJWR7DB/2QhuVZLR4EhIpLo=,tag:pzuHXGgR6Q6jlBI8orslYA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdm9MVzVBNWQ1L1c4M3lU
        VW9uakJlQW5TL0dTWWZYc1I1SEZTMlEyTEJRCjQzdlR1dlFTSUZpYkJCYzBrSHVo
        cnFTaHlXNEhHNlIvMDBnNzhXNStMemsKLS0tIERpcHdmaUY0QkNraWpxZk0zTWh1
        NzkrVmswdzluYUVxQ0JNejRJZnE5c0EKWpxYb65KQQ0hlH3wbWeATLqNNNXF/LiN
        7h8AF/r/F3o4nY4552bMsfwaiRwDu8fO9QGB7FyWSYzrSP0eVU39GA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:38:25Z"
  mac: ENC[AES256_GCM,data:NM/OyGr8I5c3YryZCxiRb5zMwQOGYodYc/1psmxBM18GGNvXwE2nwHL0Pi0Q0sfv81EwOnbHgZC/YjxkRoPOLJQ1YRzW1lunG9e3OopHKN4SAjPhx9q4qlOCJMkagaOphzkvjJnZuctPEiUwLdysFm9NX1imlXSEymBia3o3anI=,iv:QyXIRKjNgn/N79lvpdsAY6/TuYkDfO9Z+Hsw/ZE4DNA=,tag:utHA0a3bLZ9Vp6GQA1PgBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
