apiVersion: v1
kind: Secret
metadata:
  name: rackula-secret
  namespace: default
type: Opaque
stringData:
  RACKULA_API_WRITE_TOKEN: ENC[AES256_GCM,data:S1n0RX3Ljd8FIci7gIhTVj7tpsIIiiKPGk/aBihxHxCH8OBLngHoDcz/FTqMlsgDIIZjRRKFcNR29DeZQj7MCw==,iv:/KELgigAmkj+GmCKrPiWnwKh3LgMjiE8tUWlRi+clZc=,tag:MbCsTPxA1kmdyXTwVHiRjA==,type:str]
  RACKULA_AUTH_SESSION_SECRET: ENC[AES256_GCM,data:KcrEc/GXEYxVU0dz62YmUo3rJJLlS+KzWpH/SSmFx3IWj1AHrJdX4XiU74o=,iv:mtfEIyduEcEnmbOyABH7UZL+cLGoMoJJMM58pC3VZ/A=,tag:8a9g5MGvS3UkzpyANluzEQ==,type:str]
  RACKULA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Sz5PqNr6jh9uq41C4wpsW+2tRBIkWzKum5PbK2DcX5bFz1VtkJ0VyxSORvcvGYuGYKqkx2BEKbZbnf4aSxuNL1pS5YNUT0FtvtMg8uajOsVjUIN6YBUumlZNXuWEGFkuEwqtexy0AR8/UnqiANGs/ZeVOffi8q52rhbBX/EvOlk=,iv:5IMty8ye+F6TroSLDfdvmhRfBbLadPpyEQHpLYYARkg=,tag:IUOakwjISxHJfpMPjxq71w==,type:str]
  client-secret: ENC[AES256_GCM,data:P3rnU/ZBPw7Lje5L/CE556GAhVqp5tWHdw81SF3H7sdrW2Fa2JqJRnPeo1QVqcpV6q71ywnQa83rS2i2mVD0jPwMca51H7KKA5JhRcNnAswbQyllSH7xf1Gsd+ZYLLdfqFuyFW8fJlRv2gN69/vhIqwJhDfn+UJnsPk44dbOES8=,iv:UHJ1oXl6qg4Q3RuLClWgsLmyFdg/Xybmw3Qpz67GDy4=,tag:Fd1iM7e/igHilAZOj0BD4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbDZsVmxJL1E4SXBWd0Fv
        K2I3ME5nZnNjTjBJdnBJVTRlQi95V1lUYXl3CnJURm5YWk5GNDZGOHNFNS8rWkx1
        dzNUaElsUXNZb1d1MGFHNThQdTYyQ0UKLS0tIE5McHlBdnlMM2VaQlphR1Niczd2
        VWxKbjhkUDc5NXNLWWV6bnAxWlZxK3cKRFJHEWTgjh5wRgNc8W1t3//LuuLKbpsp
        l2qP/tc8myBuLyQckm0OFSuF7Mml4zdEHj7noKvLTnWKKNMrTDXOuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T12:09:07Z"
  mac: ENC[AES256_GCM,data:bldiuJozTy+uGhlChnQfp58QM0C4McRDvbc87aB5axvNpSKLLZlYJ0WCtmFcZY6wyzE1GrsFfpbFVO5/ibtt/GI8rGHzV3bNmSJOuGdMvc+kLT24TWMsA/Opky3N/J6WY0Ud5i3EEvQNOie7i6PgJqtx2h/otbeO8ttJREZxCE8=,iv:14JzGanRkpsvAN38srfYfZpopuC37RTcHkNDTKVEYdQ=,tag:w6MmOsiFSCUJM0nxTVOcmw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
