# TODO: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-credentials
  namespace: vpn
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HwzayIXvzFp8Y+ofdtFDsh72v+6W0F9jahDvWRc/qAgdMmVY8ohgU97cTow=,iv:w0l/QitLRrxD489QVoQMw2dDlCILSR1OWH1rL+U4WCQ=,tag:bZmjKihp8xHwCxMwsluSYA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:07QstieHubhQGQM=,iv:1uQ66n2UN9m7sqnykTap0Z3TowHT8pTKc//THV+ZcHo=,tag:4C/kMj3RxvKBnqvM8KBDKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K3d5TnBUQ3NiWEFyYU5x
        NzBFdUMraHNiU0puamlTdXhyd0FscWliS21rCnJ1Y0NMQllDMlc1aXVNOHozTlRH
        OTREVUM0cFlTempaZGtPUndvRFVPWHMKLS0tIEg4bThWNGk3NUMramhjOU1CTXhH
        dW5OMFZhMnA3ejRLMVM1RThneHNoZzgKPymahvVLLByDMvobbUth/wN5izmcZ376
        hRbRm0tXGz/Njtrs4cHXW3A676UEu35zNEvlR9gri+jCeEcbQQwsuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-12T08:30:37Z"
  mac: ENC[AES256_GCM,data:u4auKyAZnva49bS94Hi9wW9crlFEgiwBZHzJ28rVvxiKqLysAbJTIYjXJi7RodMTM8joA4V/qMf2q1Mw80sO01gAMXSwjkAocQ9N4MmM4HVrJ0Vy9RuITDwgACq0jjI/a9ZJ578/1BOkGOCGuyKWgSHgjt1PlaxcsLEURfNUs6A=,iv:nUteH7DlMYtW38U6gfDdt/filWckKY+LDKhVn9bDPeQ=,tag:gLYxgVHiLIOcRerWRKjdTA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
