ssh_port: 22
unattended_reboot: false
hardening_sysctl:
  kernel.dmesg_restrict: 1
  kernel.kptr_restrict: 2
  kernel.perf_event_paranoid: 2
  kernel.unprivileged_bpf_disabled: 2
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
