---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
# Recyclarr — sync des profils de qualité Sonarr/Radarr. Pas d'interface web.
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chart:
    spec:
      chart: app-template
      version: '3.7.3'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media-server
  releaseName: recyclarr
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.0
            env:
              TZ: "Europe/Paris"
              CRON_SCHEDULE: "@daily"

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn-production-v1
        accessMode: ReadWriteOnce
        size: 512Mi
        globalMounts:
          - path: /config
      recyclarr-yml:
        type: configMap
        name: recyclarr-config
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
