apiVersion: v1
kind: Secret
metadata:
  name: netbird-credentials
type: Opaque
stringData:
  postgresql-password: ENC[AES256_GCM,data:uFjeuSjoeob2mJWtrUuCZHD1sjmd/CPEwdyAyyTIxPU=,iv:gjGpVOirCx4rfLEgMwQD7oh1DHabxfBjsmNBj7X6J7s=,tag:wG/D1zdsc+5nwBhHU/Gl3g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWFHajBLM2s2UExQeC9o
        MFV5R01sYXozdURCQjVpTXNpcUhqcWtUQkFNCnd2bi82b1c4TzRQOVRoK2lJaXFG
        eEpFZEpKaWViSmZ6b1FBSXk5dDRSMEEKLS0tIFkvSVc4VU83cUlUOGtCcjBDc2lM
        c04yRm1aVnVFRnVDTWc5enFmNUdFZ28KH6DAtq3MWEwqGCCzSJU4UfucyCeauco9
        w+Gnl60hINuwN225o1KWs9XdoBfiPeqV+SuIf84pWQ0BZWEqM5Ewwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T14:17:29Z"
  mac: ENC[AES256_GCM,data:ZoCHMCkurTEL1df06fCtVEDImSA0yqXvaLcMfFXCchsK1E+xaA+MIIRUs9vTBrPgOKiQuBNMk7O1nXLIQz9nP2lQ9uqY/eQlRKuDJM+dCS/6kMrjYvNqn31nGveFMBpjJwG1r1ZLMgxRpeYcOy6K98pQlIZsoFTlhP98qL1ISFE=,iv:elkc6JDEobfIPYorgQFca4iXHt3UWkEp088OWLu0eg4=,tag:ROKe5mShPQnZyRaFUGXpBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-config
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:f6rZ3JhV/mmRq5LDHBBiV/0z0RyMF+LrZOd5CywiZEbpJHMsNqTFGtTGa1WGL/Q0HDJaJeKjqsEa2JpJeQIbXi1qtRELn9hIIROPycd9m5E9XjBB7S8ghUdeKIxLYU+5SWPeImFpf/mYmZDeAk9DlNCMp/hep8dwEs8g5n9VD4+3kwqbjGoRFnU9+itmBB0Zb/o1ERnYGLB1PtKHYC3Gx+aCoz73v48l+K4VhaJgIyyTk6udmW+Cw/tBs15TBr6p/BCyKpyQA/9ut+lKH5pfk4tMUPdWGnpCUw9BO9o2otcQf1niIKGF3kuw4Cmewvd5Nzm3+Ww+TlyKXuIicTaA1Q0ggMOpzDNciTKSfOaQPwZPmultehG0EeRrl5AJ6UqPQbwr4wUH0A+tNL7jfsskBRGydikieVgrHIwkKBjXezJdpPAc+C2vM5GZ9qjSowOcceQgQBClLC+ItrYrrhb8K4ajOcpDy3VTknEsVKlphGU+QlCS3dpcORpUHqf84X4NrQ2VCJ2UtHtYyE/ojbfACNeIHCsp6Xp8Qs2p+qOZi9TvKyguVksiTFhfrzsIES1x38QMjgcah7gTCsf08b6OXnErCCQ8ZL0F5fFixaG4xR/+/T7GLh7Ad9uj8FUeUpSeG331AaDdNH5CcDz9QaW799gZSXr2nZT7BXyL9OwBuVoNB8vmErDSkiJ87mJM6r31sImAn7sRssr81HC3gtaRc7bFzzRAlI/YXee15MxxlNb/POPlqkCsXLLsNjW0DSZ8P4FqCOLJzJx9aSGrykpAGFBv99VUs4qgaEo924C4jAqW7681WUzMUtqYTwAhYXmXu+BUlg0wzRjJzEy8K5wghjxEwTs4yXiTbQ3moeVi6hO9u1j6m70bTa9/gatJ89TpZvinYUZkNS4JZ0TrKDFTiLCoYi7NApaAwacxcL2RWHtcaQ611ijkhC99cZzJcSI6VC2/ffyxIP1cQnnrPLr9oSX/G1TmHJqzXhXgAu6ATMZEV9OsJRVvkY9PyEMV9UF7g1+1YkU1ceAPeUXzOBxXthkRg44euE/Lt+f9N66DDKWp8bk11SNOwrkzOBL40GEDnhx4lGV5f9kJyYYt1M8EiWyyf+6u3wIgH3nY9i4YBo0Tpwoy4UJ3OWnmi1zdsrdTWBhKdVX80W4yMlgjj5s4J8QAgvouZtO1b6G47BkxLHmzv3Zfgv9H09Xm+U2w0M42w4HMzXXOw5G5hdG28HbY1sxmUR6YLd97mE7VgC9XCFt0ouVFyJu/VQftrs2Wanjp9rc4fUoz3WADdbXwfzjmK6BWcUUyxVcVgn1sAawGSKzrzd11dxHfAOi3AWNbxE2deDAVCKEQ6evWm7lonXQyjpVypoqmfONJe5aDVMJqt+fTRK3v+K2kFcLznYiJc2OQ36s0WlLLUfk1aON7U+04eI6VxiYpnpQHzV5EBviKwP6f4mn2vm9i33o/BLr90rQpp+RVQDdm0hFm+h8daAzBN24tBEjtOIpx9hjBW76ZSgQUI/jqHdVZaVCUm3HGHiC3CNLrDbS6sZzn8S5zzU16TilUgH7d6A1f2rYlTYinh4C57COm0BYMkcmRo9iYyZGL34640jNPRkne4u/FjwypWhXUER1riQhMAjJ2dfDvOxzL3lsmDnWycMWFaYM3ulnHEyCCkrOPF6df1mG3BCo6z4t0xD1FKPEBduUDODRA4hyF0MVsC4VAljdNk2wutM/PR2i7H3v1XPV7x3YmHgBTIjS1arEAJKQYp1ryBw640xl3npVMpzoADOjGgFqPKcOEn2kn/q3lEM/Sak/VXCDnQM4ZmFObX4G8BpAA+Ag5FPVMyxNMgvC/q2es2q2GfWrwdRorp2lVej+pH/N0A8nbKoDhgS3Ph/QeXCMYgAFH4qHgtRNneCnv1NLY2ftoeuxyW7Ve3NGuxYoIHiA+IpoJ2rv19XVgqAyMj52ow3p/KzAUULIv4RPYl7V2ApnskxbdY7H+lGdvnw+LWaxikeGf7wrq683dmZDs2wjDon9RgNnXkG7gtcumm9Mom+ItkVpTURuuRYpW1ifRZ6FISB43IY+VTeE7YvUWUeCC+tDE8joNmEdxAZl8TDNa0gEnHLXjMiLYfm/NV00awEuKOJcFUr4ZkDsoeR5CI7ujoz9VCB95ycG9b11vsVbH4yF9TEUQ1bVBOCvhieNlhk1IvzJ1m30zOG9qm0SvQ2Dpt2YX3qWQBmtevRW2MohbpxXixIW8AYaB/N2BAlMLu1fnVAO0txei3KEUbVgiO95MARqHvHZvTjU4ex1RfLPDeZ/4CAjekV0W1/27kLY/w74K28glB28T+vhfLnSTHjq7Eyl9aEPjVRQ0x97sOqc+L1SqCg74JSt9VjzGAYjB3pRyp1jUYstCMWsI8uL/pzZAPRVy3oY=,iv:17tBiaPjen22QiEByI0fzWLjSyuwet+RrpM7fyO1Fps=,tag:jqACb0tsLrS6qPIEicAUkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWFHajBLM2s2UExQeC9o
        MFV5R01sYXozdURCQjVpTXNpcUhqcWtUQkFNCnd2bi82b1c4TzRQOVRoK2lJaXFG
        eEpFZEpKaWViSmZ6b1FBSXk5dDRSMEEKLS0tIFkvSVc4VU83cUlUOGtCcjBDc2lM
        c04yRm1aVnVFRnVDTWc5enFmNUdFZ28KH6DAtq3MWEwqGCCzSJU4UfucyCeauco9
        w+Gnl60hINuwN225o1KWs9XdoBfiPeqV+SuIf84pWQ0BZWEqM5Ewwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T14:17:29Z"
  mac: ENC[AES256_GCM,data:ZoCHMCkurTEL1df06fCtVEDImSA0yqXvaLcMfFXCchsK1E+xaA+MIIRUs9vTBrPgOKiQuBNMk7O1nXLIQz9nP2lQ9uqY/eQlRKuDJM+dCS/6kMrjYvNqn31nGveFMBpjJwG1r1ZLMgxRpeYcOy6K98pQlIZsoFTlhP98qL1ISFE=,iv:elkc6JDEobfIPYorgQFca4iXHt3UWkEp088OWLu0eg4=,tag:ROKe5mShPQnZyRaFUGXpBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
