apiVersion: v1
kind: Secret
metadata:
  name: netbird-credentials
type: Opaque
stringData:
  postgresql-password: ENC[AES256_GCM,data:cV4Khms9fUKYEbk+pgZZfyeCrdF3+ZXpyvIcF6sllSI=,iv:OFwfBYZX1kDLzehnetRmcwGHN9hCJsDs0A4/Z4jaqBE=,tag:4ueIhBQrcIu2YMQ2ivJ08g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWEM4RUZOQ0ZrcW1GNlJt
        ZTdBekc5TGpvOGIrL0c1Y2FZMzVyQllvcVFvCjh6SXRRNFd4T1gxRW5TSGVJVm9U
        bUE5d3FmUDJHRG0yR2FZNDNZWWJYbzQKLS0tIGlZeU1xZU04M3hVN2M4QzhGZ1Jw
        TmhKQ3B3TEdlUDZ1eENRRjR1VGQ2Z2cKU+NKXpZbqCGIa6SakWXxs3JsxVLJORmB
        p/CTZONq9IY9R5IYuwfTn+NIu4c+8fBVD57OP6kl18Ck8biBZkQ6JA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T14:30:59Z"
  mac: ENC[AES256_GCM,data:RSNFrIH/I2Q3hPMykEo0QBuGM2lP+xMWLEj82cVcACuzKPHp3YDoEjFuZObANgsDiYo6rCMJ1wW4fticE9+xpMZd3bDhQ/SkRY5yQxVLOfwWMdAeM6l8mSoVH6aTvgSQPXuu3dNKkjVP9PqMZVo6sKO8EF5ltTrLG79Bd/g9bz4=,iv:L7awruPjJMgQxmFyShbf6B4ZLykGOpxS+yNMUHTfFiE=,tag:cMGpWpX1F2OQ4gXUS5UYnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird-config
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:pseTcL9V+0IQEJTRtXIkKAFYHoJgmW4IEgIaGqRlf8ZSqgx4xLm8SDQ+4H+GBICtFU3InAYUN2lqbmJfi9Rn0vsGT0KxrMeDy21vwN52Waq5YPWtHW7LRn6zpY4ndW1Al3maRXsGgfwuv/PqeXHpWyM8zwY+YNRArb2KHfweXgMNxp55+Ti/I+pgadPNFA6gNlO7BAO0KjP8gSSp4/4CoTn4Nro+IFuP1nGh+cGeCn/KbnwYTtq0WhGd9Day6d9xVBvtWV1H8nOdY/ElNYYE+NaWshHtFvcBkO1z0r88L567RvojsRn7GDKzsxWR5aNvxKhIfuPEDE88ey8crkShyiEFh1nneZvvhkh+bauTHIMjcWW50KZLJtGD5Q4oRn+MwqNgJVlUYURcxHYHwJdUWUgPFeE1596JPk1/FSNcERRCTJiyK/ePhNcuyJ+j+bLiL5763ZuGHcKbfpfWivMxEzaFY30UlcdjOfYzZo0RRhBrHHF05vHk//ULE1RLCl0gdJOuBO3O2jWvaM/8iKxauE9a5fF6B2ksCZ6MeSdrktKN2B++xp/PQAymUp6hmfQ8DbvDf6dKKEXfH8KSZs2025NHQt9MUzzjtifLq641LEZJCvfhGv/ZzHNs2kTFzo/ApP4gnc/VQOWhEWmlSxdcecTyQID10X5+1hbjxU07Zo02OlsuQNsAV/YuO51MU8q7A0XIU94h9jIzJ42BDMgIcAv0DYmUEjnKoiU+GKZg7WrN156xazhMWH4PVO7hi9EcvLYyECjBf7TDy/XrZm4ZFvGlBOr/G8IlWXSyDpjy2wRRYI12Ex5/CnNl09/PcQ9bVSwrViX8Qxg2L5nolXhXEDMZnuJGtlCoL61ROzcnXNvDnOO7XA40RL+yzTCObFGIn6JwIg1FhmMONpQwD9oS964lQFI5JTMHcnVG+ckkfbkGGnZ6p5UItgtTt2c34hwhm/rltZX55diflg5esxmLtlwULD4VW+E2nPT6BgDVGlYu7AW+tCCuxv5e3c5SwXSi5FNakd2DLQDosJBMduVO2yoL+YkEg2yXyzk4v/+lRMvJyUH762+zaJG9862Hj+AHp/joliH/i+0mCLuJuKNuZyGAW0KMmX7nnShobg9Wah1EXMM/ORdv01fsp9SO9gdtPAqLNc3Q1vJsPVdudv/kPugtE+wHst1xFBeMbKS5TPOD1ccnzDRivCZsbdZ/VqSfelo2+mTmWKMHp7opKCrz/6QO4YeQa1H4AxTLGf6owq6HFb4W4xPu+MIkxix6meFhX2W/F0p/oHd9kIQn5EzX+Uy7yFXP/pPEEThj0fHG/wftJ6TEpAid4g8Y6p+eJfCWOnQFuW/jSmx8IYWHoo+ZGPLLZhPc08+1FnY6ABHngCAcwklkBeL/nTU4s6A1v1UaA1EDteND4ALlBR5l9vUVcxHKeJjrBScrTSyNo0c3fmldr/9Z+mnJY7i3Pbn2bjjZmMlBlZyojxJVlYxw+Ji37LL4HrrEJmqJNJXSpBYabq27IbuyIJH/IYsjJYDOEHIPQE+YCOeLSNSySeufBW7BQqB/Si1iO5LWcCzGYidtWOq82NWk+NZHQtLUp29rQOWQwYs0CKDQ4FwnyJxVWnC1ypCiKMHlPXbHs/Kd89buKSrpi/5NosqU953ZP96iokCif2k8uPXy6YZOgkmarG2c1IX+fViFfyLLf/FdqVFOrpsnuE8KV8BN5CxOs/Wn4d/T+oPgAnVMjEZAU6/g5RanqzfmevY3XOGCTnR1mQWDExhYxh91ZRPZbvqAUIbKwyh3wNpoAZVWWb4wYL4dvjQeSPymeriva8nry1EQUJ09GNiLRZT5v+qC4j6Hj4qo3Suwpsxzd1lnZoexhT2aN+k7W+YS2THjHN0LAcGDfcl6thTRJoXDB66S79Ifz7Dp/HraXywtvY/FL/9LJ8EZ/ZFqWHuS2rI2rw/tAoOd4Anto1dZdcYqMxQgben53Unv3UNQR1c4SQuN4UrlDQva7F+kCqZ/nvSPfm8HCalzOa0b9H0G3UbyPMWVQrLHK0SG35kHNhtszdMOq6cg5yEveAjE32g6r8mWzKXooIZqQ06aauQ1umKc9KVX5CD7JMGei9TYWYAngdPR+oFln+zUghp3+Hu9Xe5U9edq/F/GaUroTsiZJfkzZBUxhwGwv+hlZFIENgKNYEBaes5rtHprzyGut1urRAomwTtyEwBAhiiaW0MhaFHBOTT60DP2VV7qt0m9OmXCBhjKEnU1bbdNa0dZTRYKi7SApIXHRFrJdzQ7DbBBoZgU0cs3xuRE/nABfPJjXWsqrNAeG7cnclXaW4WWRKK5fjJWLrcIn3AN+zFDqO+hKwxNXmB4YEboBlc=,iv:Oz/snBsjEiud6RwFto6agTa7x7/vAynTGt28cFLIq8k=,tag:3b8E6fLlp4Mk7E1fO94ScA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWEM4RUZOQ0ZrcW1GNlJt
        ZTdBekc5TGpvOGIrL0c1Y2FZMzVyQllvcVFvCjh6SXRRNFd4T1gxRW5TSGVJVm9U
        bUE5d3FmUDJHRG0yR2FZNDNZWWJYbzQKLS0tIGlZeU1xZU04M3hVN2M4QzhGZ1Jw
        TmhKQ3B3TEdlUDZ1eENRRjR1VGQ2Z2cKU+NKXpZbqCGIa6SakWXxs3JsxVLJORmB
        p/CTZONq9IY9R5IYuwfTn+NIu4c+8fBVD57OP6kl18Ck8biBZkQ6JA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T14:30:59Z"
  mac: ENC[AES256_GCM,data:RSNFrIH/I2Q3hPMykEo0QBuGM2lP+xMWLEj82cVcACuzKPHp3YDoEjFuZObANgsDiYo6rCMJ1wW4fticE9+xpMZd3bDhQ/SkRY5yQxVLOfwWMdAeM6l8mSoVH6aTvgSQPXuu3dNKkjVP9PqMZVo6sKO8EF5ltTrLG79Bd/g9bz4=,iv:L7awruPjJMgQxmFyShbf6B4ZLykGOpxS+yNMUHTfFiE=,tag:cMGpWpX1F2OQ4gXUS5UYnw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
