---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inp-calendar-rs
spec:
  dependsOn:
    - name: inp-calendar-bot
  interval: 1h
  path: ./kubernetes/apps/inp-calendar-bot/inp-calendar-rs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: inp-calendar-bot
  wait: true
  timeout: 5m
