---
apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
spec:
  selector:
    app.kubernetes.io/name: authentik-postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authentik-postgresql
spec:
  serviceName: authentik-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authentik-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentik-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: authentik
            - name: POSTGRES_USER
              value: authentik
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-credentials
                  key: postgresql-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn-production-v1
        resources:
          requests:
            storage: 2Gi
