# Generate the values, then encrypt:
#   secret-key          : openssl rand -base64 60 | tr -d '\n'
#   postgresql-password : openssl rand -base64 32 | tr -d '\n'
#   sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-credentials
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:BvJSMvMK6q44z0a4VAsI2Lc1okkCVUEcMmv1D4dNkJVgX0u8F4QHjDRSWklwMQf6+Zj4AVhliqUSLbGNaxvivExnYqb3e2faxUNJBukAu2M=,iv:0EvU0+UOFt5kKHXPfu9bkAMolFlO/2wScLQjML1I7W8=,tag:kOOOHkGSeGYW4YzCrmMEgg==,type:str]
  postgresql-password: ENC[AES256_GCM,data:lgAT9epbl9il3qvgNKqg2XwbB0u6/krqYoAFxhOVJclKTf8VaSww5sc89E8=,iv:ADvINyTVbyhIOJgfc/WUHGwMrTFFyRn6py1bGefVetc=,tag:KZRn1at40p0xREVeP2smDw==,type:str]
  rackula-client-secret: ENC[AES256_GCM,data:wxA07udVnD4/L7AnLi+ySTn5NZFTQZAUI9xMy2l4yM8pZS9rAGlGGVV1C+gkamHEvNoDj7YcpaXPP03Z6jWL8ReZ2zrWBxfuUXTD7dFoBkzbhHt3cQmwQYv8VW9CFTEa11IkVJxXCLwd+9dcULD4Y1OKjaLA1xVDMrY8K3tZvpU=,iv:il6baKQHNagJe86V4PNu8YWW6YSXwJ9vboOmNvgi7N0=,tag:BE5meROnnvj0AIxslIB/ow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK2ZDTmljdWhTN2h0ZTVY
        Uk9CWFVIWitNRUd1VlFCQlZ5bUt1Q0xvQ2djCjhMKzU1MW5JUXgyWTIrWllGV2ZN
        UkQySTU0bkY1VEI1QldIeW1ERkhhRlEKLS0tIGJPQWtXY1RvdlN4ZzlxT0tPc3Jv
        MFp4VDNZMXkydFFwVkRoMW9jcTVzZFkKtddD1C5VSryVB6IxER15DShox+xZT5xH
        4GaEkqWJFcQoJdlb4FI7EiUBg9GJKMmG1jERPtndtBcLg6pYgQ1rnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T12:35:43Z"
  mac: ENC[AES256_GCM,data:h/3kj44FvTEAdwSx4iDuqw/LkRWTw6z23zFM9KVs0L+WUrD2k7Nlu46PI6q3btOwpEBUzXnVaHHtgbXw/jRaQRqtV6+eVbyqLL/29GMfugkdrGq5+jGruTslbfvp6+EXg5NOLy6c752Kxsv7ToD0zpzjgRz5f5JGNpAL8EkpgxA=,iv:/sPBM3gPmqte6yP8P51/H7B74r1xtIVRG3XS2Ph3pXE=,tag:3XGA2lLeB8q4mG1QZ8YkUQ==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
