---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inp-calendar-bot-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-production-v1
  resources:
    requests:
      storage: 100Mi
