apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
type: Opaque
stringData:
  NB_API_KEY: ENC[AES256_GCM,data:syl0a/B/S5INOcLkgUS5PmphkqvpxscnweL2wbCyVluiK/2YROJGbA==,iv:zwAb5izHHcgkZjdLmP04URiPBNQiD6GdE1IoAnOqFnw=,tag:IUdxtvT8RIIZyP0jeI11Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bGwwSDlFU1RXVDg3cW9F
        WHFkT0UxOFgrdVE1amxBWEp1L1M2OE9aWXl3CmlrMzcyU0dTOVdNWXhsVytHaW5U
        Z0xENVprVUVNbGR3WWZFSjgrVnJPcXMKLS0tIDhKYVZUSnNzMmtQNDh6bnRPdTEw
        aWUwY3FVeXBhbS9waG85R1FUbXVjL28KlIzIXih3QMXOPx+ws/VjAN0esIIR4bBd
        8hKU4lVdw+oZgA6A7fovG2NCGNZGB32VmH6JNmd9QCJ3gTG4f48iQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T14:23:04Z"
  mac: ENC[AES256_GCM,data:y8h4TTKy9kLlbUQFxa7Ho/wxlyhNhbonBWOCGgAeKBQ8e+BAE8y6yoDnzgDAjBC8HpcC60sNGdz1xyfSHQ8/oVbglY4XiiWb7XztKhrHLBPw/yMNmkrR5eFSRV98bWQUUElPrP6ps1vx2IHzii0XCbBHXDtFY1t0iUKJGAgUZ38=,iv:Y8pUCFVHJkxqdbSZbeBxTMDozmBft2MpQZxN1osQ160=,tag:w0Dmi4UwbFSXEXvpjlOAug==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
