# TODO: sops --encrypt --in-place secret.sops.yaml
# The value is the output of `mosquitto_passwd`, i.e. `user:$7$...` — a hash,
# not the password itself.
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: home-automation
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:61REljj4mk8FcWN27OYwtYpEqtcfL6gBbbESoCpWAq/X8MmPG9RASRxMxKY6UfmKFQMefLD4NB9qelbAaWTcVLw59eWlVzY0CvDbUDgQn63c8qI8aLCVrs9EreV0LspeomlH66dStzC57vPcF52ufZXmi8E/MalLtZ73g/pW,iv:mKST7RgdF/WHYM3nSb3eijW572dui1z4qTHmtyjjGV8=,tag:KrkiygtHxC17f+Ush2JAkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlem5ML1NlMGtIaUJEdEln
        OEpvd0h5RzZsdEVrN3dVZFJoQjdMeGVBR25nClJmbWNNTHpYa1dsaStsUXFqWWpR
        RFJaeGZqZEllZ1VUM21OcWMyTHBRdlUKLS0tIFdUV2g1K2xveXBIU3ZCRTJQRGJF
        cU5XUTVSQnhzcXNTZno0Sko1TGVxVWsKvOhvw8FBUhXNxDBuRIsze7w8cGfAecGy
        Dsbsb+Flqt6pnHo2+RT+0roYoV4Qo6ZiNCCttQYqrmghKss/daMxKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T14:17:54Z"
  mac: ENC[AES256_GCM,data:Jv1ouUWW2xmQSLHQ2L/n3yBivnhDTG2I5CEaCGj2O6KmGoVpf/0vK6+HHGS0pA6ltct3/1qYUYUYusI327cn2oc6QJjdYw992svZVhMcsKPrp3l9K9RJnAi3cmbYIG5Jv8VORXi0pYo8DsT3mfRE9RF+g5FUpJYPE9lnCc8bjLU=,iv:3bFo2cpjhJ8PrroMXr6jvJPYkIiUHxdItPMbRh9oTCA=,tag:Ctb7QZHGUgcATfpm+Sm3PA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
