# TODO: sops --encrypt --in-place secret.sops.yaml
# The value is the output of `mosquitto_passwd`, i.e. `user:$7$...` — a hash,
# not the password itself.
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: home-automation
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:yo6VtTsRVZVjjh/6OCr7DycPO7bHEQnZVia7Ine//KlPCsPNyYh8APPIhznn80I7TlxXRgqrimQbYV9OWQxC0aceiKjMjjgkUPrQ3/uZmEcN8VIN9FPKc/YFyBgOvql0eB47BjsvUqouns1cp7FE4a5GM0wxt1s1EN6kj51P5Wp4qyIWTfXkeuUiB0ixDI7rwerZ4p5rK0r8rg2zfFOU5tjMrUccYu2F/K8B1Qeb6/icDht6temYFM5hNc03RQVo3l720urVrk9gVbLU+lqTHxl4R/2PXWwgdpDIi74VNvhnyDYlv1J2Lmr2vYX53NWTv89xsmbSPgUkLjTs,iv:Q/cTdZJusxoyhi3mJ7g3WIbBbhwfNWa+ftDwrhGyoWU=,tag:Eeuy7PMXnB1mlqoTutkEfg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbWxxYnNuS2NncTNPNTdw
        cEZQMzU2TW5UUkRoN043clpGbnVyd1FBSHpZCmxZc0ZZa1AyVCs0ODJIZWVjaFIz
        VmpyR0laRDlSMGI1VmhYMGpRYi9qK1kKLS0tIEpEMFM0N2hYSEFOZWl4NUF3bnFE
        WVlPSk5qTEJyelVLQkVySlk2SndmUTQKqawS/Z3b2v3Q9KkXABzRMltv6YKUTRQs
        BpoXz+WrIZ6Rpmdg7E+TaCqp9iKXJ3v5jxgUyDjrLNYdAqz4arhQlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T15:05:50Z"
  mac: ENC[AES256_GCM,data:B5Yn8d+4yFEUcTZwXPUf2OoXM9RUL46NbSE9rXh1BpUGwWdFgGTXwlHImKURu2+2HCn5lj2PXLabYEkuGTbs069+yxvj104On6Guh7ihwRl3J/AZF27XPBC2a9as1oMQlWpOmJLgSaXUaIWGpPCBwyZ9EHJo2JJFkATv9pQhnWY=,iv:F3VII586L6MhGOk3uYtXqnA6bkxCZaKkZ220yl5JWMo=,tag:HdXyWr2j3xMQt3GmbYtQMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
