# TODO: sops --encrypt --in-place secret.sops.yaml
# The value is the output of `mosquitto_passwd`, i.e. `user:$7$...` — a hash,
# not the password itself.
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd
  namespace: home-automation
type: Opaque
stringData:
  passwd: ENC[AES256_GCM,data:9KdrS3huWShAM+xVcAQcBFA9mSiw8kBfoam9M4JSEAKJOisUboK1Z+Wg5L79Evnsfn/MAeaXoCZbwIq11Xz6k5263F3cX+OEdVfUrUt1Fkkb8r6BHy0ANW35eSMP7aF49OPDTxgWuHL+dml4MzJL3Q==,iv:r7it2h+4wvWOj+Aqg8Pb5LhcH075Vx9XlAEEfxr1qug=,tag:WGjMozoVuHGJU99qXgLHEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlem5ML1NlMGtIaUJEdEln
        OEpvd0h5RzZsdEVrN3dVZFJoQjdMeGVBR25nClJmbWNNTHpYa1dsaStsUXFqWWpR
        RFJaeGZqZEllZ1VUM21OcWMyTHBRdlUKLS0tIFdUV2g1K2xveXBIU3ZCRTJQRGJF
        cU5XUTVSQnhzcXNTZno0Sko1TGVxVWsKvOhvw8FBUhXNxDBuRIsze7w8cGfAecGy
        Dsbsb+Flqt6pnHo2+RT+0roYoV4Qo6ZiNCCttQYqrmghKss/daMxKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T12:26:49Z"
  mac: ENC[AES256_GCM,data:k2lxGNjs+C2s58ONByvURZLSbaoLBnEmDsGV76ExyVdpAw8P3v+iGnFQirZKVT0QBDUmXnNtzM1RpEvkN5hrx6xPqR/vuLqXt9FOyZqtvVQeoHjwgACylFGSnB1sJ5f+ICKtPKXnAmURnpI6o/edzp8AjaHtKeN0QHUA/ZCJ9i0=,iv:irswuCF/6rv8g48/Ha2mnT+vpru9ztC8yyta+xLEs8Y=,tag:GYYeNkwJa+TZJXL9t4FPBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
