---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab
spec:
  interval: 30m
  path: ./kubernetes/apps/devtools/gitlab/app
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  timeout: 20m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: devtools
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: gitlab
      namespace: devtools
