---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rathole-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rathole-client
  template:
    metadata:
      labels:
        app: rathole-client
    spec:
      containers:
        - name: rathole
          image: ghcr.io/rapiz1/rathole:v0.5.0
          volumeMounts:
            - name: config
              mountPath: /etc/rathole/client.toml
              subPath: client.toml
      volumes:
        - name: config
          secret:
            secretName: rathole-config
