apiVersion: v1
kind: Secret
metadata:
  name: rathole-config
stringData:
  client.toml: ENC[AES256_GCM,data:XfK1rkeb8epXHsCW+7caxxwHJpLo02y2UH7+aUBrO84TBDcSgq/P406I5dEbE88tURoTVuuz0y3PpbXqKXkvuWeJF/fRxwXtl4wf1c/v+4jdXFzmLp9h2tzAVpQIvni1DoH4cOF1MGz4Cy0bAgQtiUTj1nrqCZfJ2JsBHpog0StHPYS6a+eBz6r7lIOR0n45yK9W06XWjZwH1wj8h5YUmuedcEEiJiYBEbofeZWi15wY32oq4jA+2geGLO/I4W1gAPJfybIqv7VsYGQRvaLy,iv:HdGxEnwQ+Twlx62rIwbRYez0YiJZZO1g0Arn2YYHfos=,tag:t6iTOSoO958/U0b3UhcBbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGakRsYkoySGxHZm1QbUMz
        bUJwSnBNYVZJc0xPMXc4bVdRaitnVGFJMkZZClIvYlJ0RnhaYzFLSGlFL0o3VEl6
        dlViWkx2bkdlZmtWclZmdHdNYTcrOUkKLS0tIENHRGl5RFcwbzlWbEluVThRZWRz
        VGd3dWdlSEViWXZlcmp6RlIxNkJzd1UKXXHwd5izGEgELEA+fv1nRj7tfxNUL0rs
        XSOZ0OAARNxmhageWyoxeWhypkEcvW5zbjq9MxXW4sM0M2OWt+/4NA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T15:26:28Z"
  mac: ENC[AES256_GCM,data:fFn1WY1gNc795nyCHg7xrHJP+o9fY2DorwTk/NAHxHHyw19ZIZLHoGtfofwMybl7jeJrM+HYNlTdSBePNxVULIRBz+cvFjiLhdMJTMjH4e2TPbYaRxTozU3KK6bZwVYLUPh0btN7jPDxBvF7XdIui1awdm9RQmXUgQAFEu8/O1U=,iv:A0HCY36A7qjYbAwUXhxhAT+jlm9qdJmb2NzU6C5c9/k=,tag:dGliYw4zlGkkZ6s5OF7Z6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
