apiVersion: v1
kind: Secret
metadata:
  name: rathole-config
stringData:
  client.toml: ENC[AES256_GCM,data:JwIoQ3VAQjdmfDky7caBqPJlas2SvXHdbEZ0LSI/7Su41koIMkU4uQgxMdl/Dg1oAafMufm08uMpBSuMO7EE8Z4aIqjWGRF4YmWFv6C7Nn7FSHSbuTCtImkxvtaJTHQEHFaE4TJwHAET1hUkjPey3XXFxEcWpabpW5mIi0DbNfDmKDf3RrYNXBIKYGuUlRbRCi1v5nKP7ZiZXSB/1RWFqwjof0ADJDv1MjZcErxPL8ssTN/h2Ar+UPDhV+InH+oa3uQTQ1IA54m6fgM74LJCGQ==,iv:orAEuDNNUsYPWFWFGpo4rLL6iijjpfQfUKTQQZQb1ec=,tag:DsDLe3L3tmmsnSpK79PsxA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSjhaeWptTFp5NGFnUUlt
        WnQxN0JkeHYrY1QzWXpsV0FEU2lvU1pXMEVNCkJudmNaZnNSb0EwMGJkOGgwa01X
        RmFFK1JUYjl1R1JmcFFuYVM2ZWViR3cKLS0tIGVhYjliaEtmeXlpV09FZ3Q2YmFy
        ZUM5a2d3UUJ4cEFuTTZXeEZFakZXckkKD9ilkDfkCHO0czxVFbRXqn3O3IKsx4aS
        JQMDrubngdYZ01gyVSnz7vmfFb/S6VNOrY3G4TtB5ysT0ynImpl48A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T17:40:03Z"
  mac: ENC[AES256_GCM,data:KYLSQQnirJSpw3lGqh+90OmpRSiF/VbSx3yz8dxlwiKI8yaLHHKirn7hZJjfvykRHP0XWmNIUbWGO7l+CKJkwZ9XKjBuTPbenPw4pFbC7o3kjSDc7xtWno3gljD7Vb8HLZ0/QykMOoVWAke2nWbASkdZaf6SkLaFr+NP9SV1mWw=,iv:5llEFq9G8JCGFsYApirm93vD4MB8owQ8ePRxulNv1zc=,tag:8ckgirwYINCO+9VAGxrZeg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
