apiVersion: v1
kind: Secret
metadata:
  name: rathole-config
stringData:
  client.toml: ENC[AES256_GCM,data:G6Bv0rYOaB/vsQvjvg16A6lsR/5XuO55O1hqxmyLoI4EHksSvM9rI1iKFDOUsVcnHW/+5tSaASxqHrdUI0SsdehiWD8SwVyitgfSt+ADGifLnVB7kVIkjzvmDFWYvL2cpl2mKmUBg+Z2gquMbWrg4GPlU7O4l9vVpQ2XiC3ge52vMsxyKcYqUCBE7mz6Q1tp1ge6H6us8/P+ZgnjJ2qcM+wjiQy5wY9gPx7GoErAWYc/52owCoaPuAZm/oFlcWH+VgdUzRyfaGj0mOAF1mcq,iv:7fS2psnDFcl8x7xGrGqtDVJ5GfbFYcnIjkVn6aSOv0I=,tag:yB54RxC3grbX6g3Mhqbo2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERUIvaHZHRmJFYjMrZVcw
        bzJXWWd2eUZQeHZhbHI3YmNPdTlNZmpoU1VNCm9JMlFtMFl0MXZvSEVkWHhrVTlX
        SEdNNWNRR3Y0a1p3MnNjc0lVVDM2dWsKLS0tIFBzZFJnRHBXZXM0ZjJscnlScTNG
        bWV3UkVTNlA4NG5IVERFaVovMVYrdE0KNzUFomeMD2fKpBDP6MWWZTpIhmct/Yzm
        yz3CIlvySPbYgaqbI6yuUNY8H4JoAUCQDyV+qpWJA2YuqqyIXcaj7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-04T09:06:10Z"
  mac: ENC[AES256_GCM,data:/D0yY1iADT3/IYwwykdLVXH2he2SM3BqwAigz+4IMlu/prlwrgiPjRfePMyS4jIOot3/hX69GAGdjn9Fi+ax4XNrXpiUdfHHMlXNb20wchfWCH7TOaowMw0TJnyNLMIHxJ1dbTkFUYLIufNdwLqSQQeLGlLxnbibxse6hbrTXJQ=,iv:bosrjmuW4/tL7oGtA2UKyStyRiXnrqi8k9E95dgvyd0=,tag:Dvwzb5uZixiHrpGUodAT9Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
