---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
    spec:
      shareProcessNamespace: true
      containers:

      - name: headscale
        image: ghcr.io/juanfont/headscale:v0.28.0
        args: ["serve"]
        env:
        - name: TZ
          value: Europe/Paris
        - name: HEADSCALE_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: headscale-oidc
              key: client-secret
        ports:
        - containerPort: 47239
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale
        - name: headscale-data
          mountPath: /var/lib/headscale
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

      - name: headplane
        image: ghcr.io/tale/headplane:0.6.2-beta.5
        env:
        - name: TZ
          value: Europe/Paris
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale
        - name: headplane-config
          mountPath: /etc/headplane/config.yaml
          subPath: config.yaml
        - name: headplane-oidc
          mountPath: /etc/headplane/cookie-secret
          subPath: cookie-secret
        - name: headplane-oidc
          mountPath: /etc/headplane/api-key
          subPath: api-key
        - name: headplane-oidc
          mountPath: /etc/headplane/oidc-client-secret
          subPath: client-secret
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true

      volumes:
      - name: headscale-config
        configMap:
          name: headscale-config
      - name: headscale-data
        persistentVolumeClaim:
          claimName: headscale-data
      - name: headplane-config
        configMap:
          name: headplane-config
      - name: headplane-oidc
        secret:
          secretName: headplane-oidc
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
