---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane-config
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      cookie_secure: false
      cookie_secret_path: "/etc/headplane/cookie-secret"

    headscale:
      url: "http://localhost:47239"
      config_path: "/etc/headscale/config.yaml"

    integration:
      proc:
        enabled: true

    oidc:
      enabled: true
      issuer: "https://authentik.linderis.fr/application/o/headplane/"
      client_id: "wohme7gfdOpx2Ho4xAQxUIWU2SEBdYJchuBVcENg"
      client_secret_path: "/etc/headplane/oidc-client-secret"
      headscale_api_key_path: "/etc/headplane/api-key"
      disable_api_key_login: true
      use_pkce: true
      scope: "openid email profile"
