apiVersion: v1
kind: Secret
metadata:
  name: headscale-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:1+mDK0VEQIIxBUXEcGSZnxtHRPVaBrywtb4XdR14XBcnkMuJjXfRZSaEbRJ72gHcQD44N7vjpmDWQT8izM3gwVz4XkSpP2C5Qepj33yTCXY4Rqgi3c7u/ExwYVvCk+eM0pEJ68tdP3laUHlPHvZzKtddv9QaHWbn6W9YRLVH1Y8=,iv:MJ2yrTxakD+bgCQpbIPzNPHgQZK/ldYTkAmEwTeiQcM=,tag:uRBM8fS7yVST6gSYylIGdg==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU2tkaWlrdzBlM3ZMWlY4
        bEc4akJJelB0b3U5bkNOQWxyVEVnM2VBd0NnCnJkMzhuUk56cXdDT0dlQlp2elFJ
        N2FLQS9sV0FaR21WTnFuaE9hS0E4TncKLS0tIDd5akwxK0Q3dUZIQ0FYRlFlQ2hv
        NFp1WmJjaFE0QmxaOWxaTEZxWXhQQjQK/jUleF6UarIKSlj3SAQpS6Xo3XuEzFub
        3yN5c66KN+aAOCNpWbDbXgVs3xFO/Fe7tOjaPRFOH9KJklcgnOdUrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T19:52:24Z"
  mac: ENC[AES256_GCM,data:J6Rt93z/xmwY04duPISfsYOeUZKH6F9frHK4lthJIDA1d0yoZdoqiMUy8JZ1lnKsWO8T0hb543K56yjrAjWccqizgsb+1otQh/B7kLHLs/w+nNg+VDi5AucpaFi49jz/s/No++V2DCc4kJTVhOI/VzxZieXGV8mDZhgeCPQimVA=,iv:S8VWRKt722j6+F7Hp2hnNfr16XSxLXkzH93Au0xxtkU=,tag:jFl0zOwohydHI6IypySm/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
