apiVersion: v1
kind: Secret
metadata:
  name: headscale-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:zXSDgX09Y2DXYhyFIWG+4Y23K6yF6G/OBkf0NIT5AGkytCwWVqCqVlYpkqypD1Q0pzfP8XYLHt0K3okRW7ugraA7EFSBXiSsyVonpX/B1sBKkAxF7f++oP2F3xiwo4oE/VLVSJodZo7U1Y9Dm5TtSZjh8oo+z+Zx/kj4sAwaFiI=,iv:1REC0LfeGLrW5FUMw+ZcPibubbrEwHEPMSZg961Q7FY=,tag:0TehbYaZTFmlD3zsIWeJiA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUZzRk8xTWFvbXg2Ui9J
        V3pyNjhPVFB6OGVNZWFUTk43Wk92NXdMeDBFCkFkV0ptRHlpREowT0dPZ1NPa3Rs
        R1JmdFV0aDU3ZWp6YmtocndTUUtxcFUKLS0tIGZOT2w0M0xXOGg0a1VqTmhsaEdG
        M25ZbHdtMkpUYnJaQWtKT3ZwajNoMmsK969Vn5ilIRiNj8XxyWBJjj4OFj4KL0SF
        iRGrgPmtzLGBWVaaxEwamf0YcLr43tVDbupn5JQ6mSuhaQiaVAH0Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T13:17:04Z"
  mac: ENC[AES256_GCM,data:TIBAmvTBeomXqZ8GNuabqNt6ntTCN8F77fwxx6yF+Rw87j2UMyp0JF8XnHmL03T4Up0Z69RTK6SjLi9qMVXrrzpNqxNH5b6D+M2Oykiz6BEIz2iaf3589bKfscY1yTa8EnBcgPxmSV/EO3KNJl/XdkXbzyWjb5+572MRD2y5DMU=,iv:+YzsZdboOM3+IzuWeME2MspwoG5PCbUPGYZwiRCmS2Y=,tag:Hs938caVC6K7dV9FBS08HA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:3hn8gZsratXxk42p46a5JDFOnVV5LNARC6+eg+aaCL7MlL48czRpfRuCg9Adjr3zYC1vmUuKb0R7FOwk0SJ+FQqUTQjfCPpDBjx5iGVaz1biL192F0is3OWWd9JYzUPHRo0BUAxMZQDePzLc3YelwKU+Ra0DITp6D+OuXjhpPEw=,iv:iYK8mBjSHOBbywDPNaMNa+oxpVIxvszOwzTcn/nVa+o=,tag:3HryqNRC/RzSEf9GHY/cwg==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMUZzRk8xTWFvbXg2Ui9J
        V3pyNjhPVFB6OGVNZWFUTk43Wk92NXdMeDBFCkFkV0ptRHlpREowT0dPZ1NPa3Rs
        R1JmdFV0aDU3ZWp6YmtocndTUUtxcFUKLS0tIGZOT2w0M0xXOGg0a1VqTmhsaEdG
        M25ZbHdtMkpUYnJaQWtKT3ZwajNoMmsK969Vn5ilIRiNj8XxyWBJjj4OFj4KL0SF
        iRGrgPmtzLGBWVaaxEwamf0YcLr43tVDbupn5JQ6mSuhaQiaVAH0Bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T13:17:04Z"
  mac: ENC[AES256_GCM,data:TIBAmvTBeomXqZ8GNuabqNt6ntTCN8F77fwxx6yF+Rw87j2UMyp0JF8XnHmL03T4Up0Z69RTK6SjLi9qMVXrrzpNqxNH5b6D+M2Oykiz6BEIz2iaf3589bKfscY1yTa8EnBcgPxmSV/EO3KNJl/XdkXbzyWjb5+572MRD2y5DMU=,iv:+YzsZdboOM3+IzuWeME2MspwoG5PCbUPGYZwiRCmS2Y=,tag:Hs938caVC6K7dV9FBS08HA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
