apiVersion: v1
kind: Secret
metadata:
  name: headscale-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:U41Zc0ByGwm5ZnsCYoY+w2qp7QC44OqhSziDyz0xRw6MtDPv+udIqqZyP1ckMK8gsu+jCcnAr0E0/y/xl490G/6XddMjx9mlKNQnNu3NyYblpThPYxWKhExti8eRglg5lYzh5OcfzyByuhCfsjAlu4jo9/3jC67sZqpOksZE6V8=,iv:6wA5F4OqKNgJJWEJPcJ78lMCuZvZNRZBZiXV0QRXCEA=,tag:Vyel3AqMf/oJehxDiaOQvg==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TnkwcmFjYUF0bGNXbjh3
        OFhTK3V1ZFVHSUw0R0t4YWFtVlZUM3Y1WWlrCm92SVlGbmR1QzJlMHRVMDg0NVlq
        L0FPNWxCSUVzd20xZkQwOUxmeUVZNU0KLS0tIEg0VjFyRzA5VzVhdGJZcEV2UUV5
        SmRsUENKM2wvem11Vk1lWmo3ZHh2SEEKMlxiIfM425G3B+Ik8Aqbc4JNG5mXqynH
        4/aUxcMrTjZV9xY3DZocZ2I5kQOx5eN/mgWJTlKkuVgA0txlo+3bkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T14:45:31Z"
  mac: ENC[AES256_GCM,data:3vh63b7pPoKgbycX8FD+FG19D03RoDhXcxnzNBY45IpKSrU69hoZoEtm2ySAvVzENE2wwXOO3RsFhSw4e8q54TxcCQ9RTinPt+8clMokxNYLzhV3QHCrdBUdQ2Mc/pChvJQ9cqs8bA5rSVOuMq8Dg/ISi0MW/nrFMkmr5ns6ajw=,iv:P6TmscOZF433w9ueULfkxQ4IkOMh64IVg5qj6ofl8YQ=,tag:Qi1YE5TlT8RQCfdn/1AcFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ocKrETspEFlk3UjHMasJ8chKYp3Hxwxw3cd4XuGI1HQlngBUUPpAf4ngrkNEI17RZP7COvg56DQIjTmTPhWOhJdVfmJNDJchwc0/nnvLnKDfJIOM9P+ydWTjunC+eC9ocP/t5HxE+SM2mbhzAnDGn1kQ5SkXxi+hvHBHY6bdGAc=,iv:P+CECW/2EL14rw4rGaUMNOC/rm1V5rlxelwZs6ar58c=,tag:jWxLfuPSX4RDbdM0Zjdn8Q==,type:str]
  api-key: ENC[AES256_GCM,data:jFGIwZXTZZgPehg4JeUDkWGT8GuB7eutRGDv6p3nLUR6onBurULeoNPduF4wxe7js1RWQB0jNfvL7dklv5ic/2teMiwqWGiMibeU7xU4eWi5B2BoNQ7R,iv:hb65ozPmCynCxXHhpVkAXbUcHZinmHU7fhOCr/9niRE=,tag:dMU56dTLmPmps1rIDPhVAg==,type:str]
  cookie-secret: ENC[AES256_GCM,data:dbu5HIBbb/FjAldnSU4fiLSTE2p1RedAySUwJFIHdhQ=,iv:bb1rYdzqek7KeSBh1l+gMp47h1A+ZC72kEipE/IzCBE=,tag:48AgB6fZPaKCr/+qZznxzg==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TnkwcmFjYUF0bGNXbjh3
        OFhTK3V1ZFVHSUw0R0t4YWFtVlZUM3Y1WWlrCm92SVlGbmR1QzJlMHRVMDg0NVlq
        L0FPNWxCSUVzd20xZkQwOUxmeUVZNU0KLS0tIEg0VjFyRzA5VzVhdGJZcEV2UUV5
        SmRsUENKM2wvem11Vk1lWmo3ZHh2SEEKMlxiIfM425G3B+Ik8Aqbc4JNG5mXqynH
        4/aUxcMrTjZV9xY3DZocZ2I5kQOx5eN/mgWJTlKkuVgA0txlo+3bkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T14:45:31Z"
  mac: ENC[AES256_GCM,data:3vh63b7pPoKgbycX8FD+FG19D03RoDhXcxnzNBY45IpKSrU69hoZoEtm2ySAvVzENE2wwXOO3RsFhSw4e8q54TxcCQ9RTinPt+8clMokxNYLzhV3QHCrdBUdQ2Mc/pChvJQ9cqs8bA5rSVOuMq8Dg/ISi0MW/nrFMkmr5ns6ajw=,iv:P6TmscOZF433w9ueULfkxQ4IkOMh64IVg5qj6ofl8YQ=,tag:Qi1YE5TlT8RQCfdn/1AcFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
