# Create the API token on the Proxmox host, then fill this in with `sops edit`:
#   pveum user add prometheus@pve
#   pveum aclmod / --user prometheus@pve --role PVEAuditor
#   pveum user token add prometheus@pve monitoring --privsep 0
apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-config
type: Opaque
stringData:
  pve.yml: ENC[AES256_GCM,data:8Tjc6AzUMgjpUMJieKnePE7vY0hXeuzwtGOlxOXkD1u8a8JIWhUMSIV1Jd/BKhPG1wwH4tWWdkw3KpZ7imS/hNc4aLYfD1+swhb2HvIYzIwkP3E7Pa1nBOmGEQMEYeFTlIiRYjvzQ1V7JwWCCjoSI6ORpOlKClPhbMypg/LuR7Gs,iv:YNTb40q7ctT+mVbqdaFSyyPknkN6XfdkI+74G6veuZM=,tag:Y6dt2T3PWTxqSGiLxJqAFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZzZkNFhRNVNVVmdXT2My
        UGZjamZ2VEViN3VBSnUxS1djM3R5OVRma2xBCm9qSW5HSmVpbXhHUXR5TWlNZlZV
        K1A0Z084ckFzaXd6UjRZNnE5M2hWQncKLS0tIGN6RG5aT09XSFdLcG4raTBpWHkz
        ejgyaG12OEdscTFHRWdtMXM2SkNveUkK2UA2BbvQnXVDvN6PSVeA4RXAFTu/M3P+
        2zzHxoOzdA5P+4etW3yzvc9TQ30fCXRT/jP1KCidK6N7eipqSf8Omw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:42:22Z"
  mac: ENC[AES256_GCM,data:p3J4iXPPa09W4sQfSxJIJ8NoAnfhQvHG+R/RqvjD/oe//F6DQddczZvFu0xYLbWfI2gv71s9cN4Tio+R8wl4Zj12WoEeIaHhuK7ciH03oYwApcLvJZisdMrx5C6CMZRn+qQ7Zpd6S0+9AqtPFAu8pHS18SA2+GZXiuMvjK2uu6o=,iv:/LZe6OoHL4ot0r0MJM1SQYuAX4mzb+A0UXtV9tYC+lg=,tag:EwWTsTm8U/oVacFhuIjxhQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
