# Create the API token on the Proxmox host, then fill this in with `sops edit`:
#   pveum user add prometheus@pve
#   pveum aclmod / --user prometheus@pve --role PVEAuditor
#   pveum user token add prometheus@pve monitoring --privsep 0
apiVersion: v1
kind: Secret
metadata:
  name: pve-exporter-config
type: Opaque
stringData:
  pve.yml: ENC[AES256_GCM,data:B9EWA1oN9bBu4cWjXiBjC18SNpNeNHQhbli23vIwb7rTh8Jn+SnKasR4KZ2xk/PloeJKqVSjTwN0qS5j+dwumethppuNX6VwshydIuun0xT61Nc/6NFtl8Vnk4+7HRpi26DVEeVQkg==,iv:M2GsAEmtkOJxEZdwR3cfCOSsMwiWeJwESeh/fV0QTqo=,tag:29Y32Ig+0sEIEkipo0lczA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZzZkNFhRNVNVVmdXT2My
        UGZjamZ2VEViN3VBSnUxS1djM3R5OVRma2xBCm9qSW5HSmVpbXhHUXR5TWlNZlZV
        K1A0Z084ckFzaXd6UjRZNnE5M2hWQncKLS0tIGN6RG5aT09XSFdLcG4raTBpWHkz
        ejgyaG12OEdscTFHRWdtMXM2SkNveUkK2UA2BbvQnXVDvN6PSVeA4RXAFTu/M3P+
        2zzHxoOzdA5P+4etW3yzvc9TQ30fCXRT/jP1KCidK6N7eipqSf8Omw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:36:56Z"
  mac: ENC[AES256_GCM,data:beJAp/8W55DIqqrsDFfA/4gcIWxlJ+zunSHgARtOCSc0dH/uNlR18djPClftq3BquQm2nz1pWvpwnjZHh8KLYL97nFuxzZtT+fAmdCxoiU5P1HYi/8uFZytaGoIgZh15hg2EkMvvzv6UVO6csgylNlHuutQsp/XvUTLNnqbgWrs=,iv:jSoT49pouYJ98BR4wOYOnlLkmJ93E2mFowVOrn+e7vs=,tag:6+mGJqgV+duPS8Fn3bK3ng==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
