# Générer la clé dans headscale puis chiffrer ce fichier :
#   sops --encrypt --in-place secret.sops.yaml
#
# Créer la pre-auth key dans headscale :
#   headscale preauthkeys create --user <user> --reusable --expiration 0
# Ou via Headplane : /admin → Pre-auth keys
apiVersion: v1
kind: Secret
metadata:
  name: subnet-router-secret
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:gydSO0igMAiO6ehXgVX4s2aFOtLPimNk7Hr6YuXIxKW5TtV1xJyL9xBECWEtyz71q716ODGob5hO9IIZ1Js//Fk7EQgMaYPea2qNTlIs5oulZu5RVz1tpA==,iv:5gmTrIfRvRDJ4wXRbjiGrIw3r82xxVgd+3ymtGr6N9w=,tag:Wc/UP+iOw6oC5RDBA7Dmbw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKci9tRytScjNCY1phSTZT
        NVZublh4S1VtOC9WVElxZWQ4RitMYmtKUEZjCmFvaUFHNjV4ZEg0eFNVY1BqUGNt
        UzBMSHpJSXIzR3U2Z2d2ZTZEbVhiSU0KLS0tIGdPWnJGQTFEd2g4TFlFLzlmb1Rz
        WUtKc3ArRW1EeVJQdDZwR0hra1l2K0EKd/DOSXReM2ct3+07cqpzdPB5bWTpiijL
        RLVYdXYtUjuBnn3Jqh3KkCP4ehsSoJ+Lo27GjyZ/KDyYssKSj51JHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T14:16:23Z"
  mac: ENC[AES256_GCM,data:j4NxogCc/XQ7E+ufQBaC0pIZmLEwL0bS/zQQ9YPMZYnXarNYQDrYK31+eC5Yrw3xE6xsgJ/wqchr2ohaiMWj+Qlc8bc/WovWvX6B909jhoTNkzJIk9DRcsnbc4Fwv/xj4BcjK18NF9qGCz4L5n+67K6vJcp807VxQvChsHQXZs8=,iv:9jmKmtzTYMejZvsNerKTcPfMtVw5hnB/xGi1SrIUEe0=,tag:WXAniVf0DMMlxU4r99d1gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
