---
apiVersion: v1
kind: Service
metadata:
  name: subnet-router-wireguard
  annotations:
    lbipam.cilium.io/ips: 10.25.50.121
spec:
  type: LoadBalancer
  selector:
    app: subnet-router
  ports:
    - port: 41641
      protocol: UDP
      targetPort: 41641
