# Outpost API token from Applications -> Outposts -> View Deployment Info.
apiVersion: v1
kind: Secret
metadata:
  name: ldap-outpost
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:JG8zd25tUyiyJIP62+9c6fne6srlwDEqYkxrg8R5S2Kp6/PDRDjveU5CyIZPuan1sJ+7nC60DJPsDWyw,iv:7PqqjuJZkuyJpnRHfROEkJ8PQEWvoYh1Ct87tXYs/IE=,tag:yd8nUAZCdxlbAau1B5pnjA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTFZORTJmN2FVdjh5aUds
        WnNUYWFXTGx5dldVdWY4Y3NUTHhNd0ttYzE4ClpWaXRSMkV3eWtpdC9GcnNNZUpm
        enBINjFJbGRKc2l4c1R3TXNGaElZUTgKLS0tIDdyZTVjZXFPcmkvWEdodmV6ZTRN
        L2E3V0NubDVsRUVkRTVtblFIUHluK2sKAdWpO5kL9lKVUmuk462Ysg/yTc5BjxHm
        I/04sgYaNWDROEqGSIfGiCcNSNnCoJarQYgVGC029zCuZsMCVqFx9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T11:39:13Z"
  mac: ENC[AES256_GCM,data:gQpTBmsv8sB5SPRed/ypNKpImrUR/Mu1awrMUZGKi+pGQsc6LmOmNXQwiah0sqEaQjHDYsZC8qas9lYmPQJN1IXS64SQP+pzKrr8RI/k6mFrtqzWpycMkBeCEkx3KIdh7I6Ls+0U7/b6RuTf59df9Rxt4dKvlyws0tkn/tD+9/8=,iv:VnUzVZTrHbuuhV5JDhQk/X18x2x651fAA2qsVzsmDAg=,tag:P8f7dve50/cluSH9pV3/eQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
