---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-green
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: kube-green
      version: v0.7.1
      sourceRef:
        kind: HelmRepository
        name: kube-green
      interval: 1h
  values:
    manager:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
    certManager:
      enabled: true
