---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-famille
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: backup-drive-famille
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-photos
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: backup-drive-photos
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-public
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: backup-drive-public
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-homes
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: backup-drive-homes
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-backups
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: backup-drive-backups
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-drive-cache
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-production-v1
  resources:
    requests:
      storage: 20Gi
