---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-drive-famille
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - seal
    - ro
    - dir_mode=0755
    - file_mode=0644
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: lin-nas-01.${DOMAIN}#backup-drive-famille#Famille
    volumeAttributes:
      source: //lin-nas-01.${DOMAIN}/Famille
    nodeStageSecretRef:
      name: backup-drive-secrets
      namespace: media-server
  claimRef:
    namespace: media-server
    name: backup-drive-famille
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-drive-photos
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - seal
    - ro
    - dir_mode=0755
    - file_mode=0644
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: lin-nas-01.${DOMAIN}#backup-drive-photos#Photos
    volumeAttributes:
      source: //lin-nas-01.${DOMAIN}/Photos
    nodeStageSecretRef:
      name: backup-drive-secrets
      namespace: media-server
  claimRef:
    namespace: media-server
    name: backup-drive-photos
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-drive-public
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - seal
    - ro
    - dir_mode=0755
    - file_mode=0644
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: lin-nas-01.${DOMAIN}#backup-drive-public#Public
    volumeAttributes:
      source: //lin-nas-01.${DOMAIN}/Public
    nodeStageSecretRef:
      name: backup-drive-secrets
      namespace: media-server
  claimRef:
    namespace: media-server
    name: backup-drive-public
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-drive-homes
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - seal
    - ro
    - dir_mode=0755
    - file_mode=0644
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: lin-nas-01.${DOMAIN}#backup-drive-homes#User Homes
    volumeAttributes:
      source: //lin-nas-01.${DOMAIN}/User Homes
    nodeStageSecretRef:
      name: backup-drive-secrets
      namespace: media-server
  claimRef:
    namespace: media-server
    name: backup-drive-homes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-drive-backups
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - seal
    - ro
    - dir_mode=0755
    - file_mode=0644
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: lin-nas-01.${DOMAIN}#backup-drive-backups#Backups
    volumeAttributes:
      source: //lin-nas-01.${DOMAIN}/Backups
    nodeStageSecretRef:
      name: backup-drive-secrets
      namespace: media-server
  claimRef:
    namespace: media-server
    name: backup-drive-backups
