apiVersion: v1
kind: Secret
metadata:
  name: backup-drive-secrets
  namespace: media-server
type: Opaque
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:khlPOXCxBqQIRCxKSEhEwb8TEnS5OCTlAF9/jwuGjJvZuJLTt6Cev4LW1u8=,iv:NJnR77YYk6j3QZuUkurG3h32lbcQk9Y8pwjHStu2+t0=,tag:JWcsUcksR/PAeL2s7/1jEw==,type:str]
  RCLONE_CONFIG_DRIVE_CLIENT_ID: ENC[AES256_GCM,data:x92u0fbwbCw8MAasMSsUwgWtoJuhvL0rDSw/6NnylvM1mTGfucnR9rn3cLCde9j0iS7n/T4dRcRbmgPzbgoiPcbYQNSGNBI=,iv:GLY9NO+TSxtlZEnRaLOsBV6wT5hbRGpD9DnMxeaJzTA=,tag:wc9BmrIByWV+rpKNHVcVBQ==,type:str]
  RCLONE_CONFIG_DRIVE_CLIENT_SECRET: ENC[AES256_GCM,data:qRKNLK+8xH0PfbTdKazZHPhMdBZnJTrLugBbvhZfROc97zY=,iv:efip8h5EKj8CK7AhGB+EEXP6ap3yxmqwG1RrsGZkynQ=,tag:TQ1B1cOYNr8ERpd9lpK6Lg==,type:str]
  RCLONE_CONFIG_DRIVE_TOKEN: ENC[AES256_GCM,data:bo06SVQWLrBuJWddoq4sn3J8dT5EEOVJtLOn4GPEpu4ZmamDoYmjXKj3aKSFSvLRYbnE/3dR2mEQhjH8ty9wYGmVNcoCcefwTjMuZTsyaeGVK5gqncOku3Jz6NCVUsgYKR5U//hlXv00nlA/qxk8fZKECp2kcJlz1EsWd20ec44jPmNK7z/nxbYx7qFrjz7/dGz1t9okyD4sa8lstddkJwUjaDC8qtrSgFCFIdweL9u9r6n1rg3Ffk8chfgCJXjB7bmZ2ho3UlB10fVEb8xRpN0sTgF3iNnhTf4nrFm4hPSdiMMnObGOW3kWQ0SNby04z4F2DbWchqofiNCaMdm8J8iVGLL4uPtyQQbXmqaeOa7zhMalsmNrx4qmsiCYHFmhJvGy9K30qwRekb2UvHaFoBb2SOZng0plodKokTknfSzHo9YKcwiENvIDADJwZGoqd1i+UXRWfU1w0UF2A/C6r4YybeNFMHGfLDg686lzPGkKGYTzAUmWZ20Lv3ZNmPb6QW2FBK41azvP1eC1j6CJ/3PRr8nD+50au0GhMZ7e8f4c6PoUH6H5Ybmo2CK35/zfaxrrY6+86HVFVZmPdD4E+faqHUAZurP+qM7ntir37PQ6bf1os10lo2szhLxIkR1JtA==,iv:ASo2NtOzOn3UrwAnMo5FJ08wSJ97KYY+A/rBlYF79Ho=,tag:O33CsLwgH11ZvIsxvzcufg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekpJWlJYbWpTOGZtTnNI
        M0kvZVJZR1JITlRoai9oVEl6WU8xOUtBOEZFClNEcVltejJXU3lBaVBVdjY1cStv
        blZ0R2pTZjlmMFhyRWJ0NkpVV2swMm8KLS0tIDVaY3I4NnkzMTU1clVqekllajYw
        MmRKSW43TEF6aDRXb1NUNjU1VWwyeUUKuZVTqLIHhJxREiEEY+MQdOA5+7ihZyaa
        ucQy4JbIFgBegYoBF0uLtMEzWEoTSQ0Zz79Za4rQ5ywIL22ajvK4nA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T19:05:59Z"
  mac: ENC[AES256_GCM,data:/mTa6L1Fq5Mbcn+dBM/lGRs0qVaw9AjlbuMmFhr8dT6WLuQNO6M4+CF0MxtL2wuYR1mi2fL8l2cTrkim5I5IK1/un9fdxFsbZbeyGEJ3XLHWtCfM35G1y/5H9QrKTY7HdzMjwnBomSfGtkUnpeh4dD6WUZSNQy6WzAUTjFq5QFY=,iv:+EEwdCfQJ2XBY/8h2z5SNsAZaPGtbb4sF53OdHkiRkk=,tag:rEvHy1A0JiHBH8RJYMc/xw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
