apiVersion: v1
kind: Secret
metadata:
  name: backup-drive-secrets
  namespace: media-server
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:g7zcaWKf53TkpQ==,iv:2guSOG7BHthVgf3z9hhaQuTixkBYysBbdhDxcO3fAjE=,tag:pI6uXCZ/Lfv+530x6X9mTg==,type:str]
  password: ENC[AES256_GCM,data:R7mwbOnhMGtn9eabT6qMMW+G750=,iv:jWOlkzQluPSGvPuGg8ZukujPq2k6nm6g6Y7LJxgMNpI=,tag:YYu43JAzR7cxUbdYeoF3VQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:OIS8uDEWZwHp+36TswqHD+oAQ7y5nyFNhP6yfMd3ZIt3fntWk2TnUWvN5aUvWFxpERsVWN/QLLRfffUlX8YC4A==,iv:wcGh0vWJuW28HjpSPyhHhMKjUdRLdTU9osQA+73ipdQ=,tag:wlF4qHmSPu3+wv3j058ppw==,type:str]
  RCLONE_CONFIG_DRIVE_CLIENT_ID: ENC[AES256_GCM,data:am/Q3wX5yRDNqJ12v15VN7cEkkpf4pjARn58FmiwBKYOagNDhc44XCa1F9B22HM075R7pAC+oAUhnC5cHwBd336GsDtszWI=,iv:xnNXqbP2m6wsKJwWuTWlBVhRRHbyBAujOCaLoWmBkrw=,tag:qZpa/yE/G4vo2J0H5Czt3Q==,type:str]
  RCLONE_CONFIG_DRIVE_CLIENT_SECRET: ENC[AES256_GCM,data:PdOcdL3yLtl2iMdDwMvQgwhZIQEsm3WgiytLdZUnYgWAOdk=,iv:7OADZzZo+OYEkHmKHTngjHRKmSC0J9aWEmiw7TjWANc=,tag:PWq2ohqPqEDC6JVKUik6pg==,type:str]
  RCLONE_CONFIG_DRIVE_TOKEN: ENC[AES256_GCM,data:XrVpyrHmOl1+/QXT4D8Ej+d2zyblyw4MwZEQovi/nvh3QeWa0jrKWKgL4ZrCR5kWcCZe6f5D92TvCEaFsJyAE+XvYPhy4GbJkZAeKe9EC8zBL9iAvEjDzWVVjkfV3rzGJArHb2qEE/g2wK5wX+R50m7U51xctBTL2tLS1bV3t/PQP66i92IvHL21gdSfoKfnqdkeZrR+c7t1vRFraGO1CEUj+YMcDeiUynFjo7d9Gm+SYWHqkztZTgPhJ1VjeLRECI8GKV8S8Tk2DTQi7EsX+P8t75htHh0Dl32au40mC0TloEYUUNev4BqeRlI15vldMnjliglWzklARHZIZnGr0RSm289WS8hVXWZr8xtPvezc+uRrN1SD6hXg9a9kb7C1DpSJr3XUt/FCFq17o6dV6ZlXnCpaOrm1IxKyZWkuO5f52Nd4RlZrH3r2kJg1hMAn4lJjnpZAnXZ2rivzVIE1JEmKPa9R03642rQOs3WCET9GKcsE6HLkMeJ8F0d5+UcniqO0R5x9v3npV67gQ/0dRndjX3XaAc3qU6NwXtkxkuNBLGBiCp1AWeJttDtjEvORyw/0EQ29muS0YSScWQTqXO1rmWJhcrJq9TS5DWHhhF7Z9J1oE5w4QqAsMBsi+rSrkQ==,iv:WHicVcVNFzVPgpiNexRP+tDamUlXnkFctOER4VBBQWA=,tag:xQQOOYqWl6DUlQJ+TlZvVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVNCZFZwc3dIOC8yWktw
        NlJPZG8zbHZqdDY0ODJRVm1WYzdTOWFUM0FBClRsR2M5dTZndXRGUHUvbXVpTUpq
        dkxhSThEaVhaUDJoZUtGWUJjSUpEeGsKLS0tIDB5NE5jSWF5L2ErZGlFN09nUXRl
        ZHVZZ2F4VjlBSGlCbW0wT0tDTUhmTFkKHnKFkkWCc2dMrnMitACMT/BegHaKbTQ9
        waraC50XH8vYTyPvufaUilIS2BsnLLXGnt+IRVR5B7fwgBE0ZYZISw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-01T19:04:41Z"
  mac: ENC[AES256_GCM,data:Jo3LPpdZ/wG+pPa6ecZZxfP+ROkz4VO8xI0rraEBgkV0IA2UX29Aw46gNunWiKg37LDKdAtzyqWFADXPSCJXPqf6zQxJFHiGQQ6B7gcTskJhoUlyMGjcj0aA/DoTDqEdRPURzTkbVPy4s2/kXW8sOZqRsdrhzLDFk2zO9REyySY=,iv:rU6RhMWhZe5hM8kIN9N46HoXs+9CPLlgdJ2ugugjd6w=,tag:k+9nCaoTL6ZgWAt/o0i3cA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
