# Overrides the mqtt.user / mqtt.password kept in the PVC configuration.yaml.
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
  namespace: home-automation
type: Opaque
stringData:
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:73Bt3JeOy/34Wlc=,iv:hf/gAwlprGdFzGznmUS9w57+OBoHrAhuYsuIUNzEDv0=,tag:6uUX0DjBSQ2He+mx/39nqQ==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:kIQRjl4UIZiasBDIcDSkgOrTwf/FT9rl0Q==,iv:Ozm2zZBWpI7JOvbu+ySvBzppzBbrCGd6v6eGdkaGMtQ=,tag:Rtbn4TC92dR0svrQg/spjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDE4QUhtUG1GR01sTGhD
        MDl3SkRJU2pNaktFaDQzOStUekxLVmNZS2k4CmNYMHNZdVdHcFVXMzdTQ2lnZGN0
        cjZCRkZHTVBUVmxrc2NZb28zNVJIN3MKLS0tIEo5WnVBbnBuWWRjT1k2TXk3Z25y
        bUxqbjlNUHkrRlhNdDM0UGJoTjc0WGcKsGxd0mZDuuu47v5+8PY+IL4mhKTgS6H0
        GC+E/4Iv88d5obOcRM0ocdXDXcumo9qITHjVTgtbnlOlJ+4Tel94Fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T15:06:55Z"
  mac: ENC[AES256_GCM,data:gWXixCQjq/rYBRfXZBeuMAmwDbp5VoC71qFOFDVWqqMWLzMzV+++gFKm1QnVPX7wAfYfwd34xrr+G+GV1Z2hgJXzdHm5v0vRcz7rhknzl4++0uP8clqfWXxyANJQYnY2MfLrbFlrpfUHohhYmFVAMwBwm00AQkeaGjJgueBpIyU=,iv:jWFg+GxQUu5iaDyrBj9YfN/VexN58i/6pOoDmGDlrAw=,tag:lq/oFSJv+fZxuGl7DNtm0A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
