# TODO: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-credentials
  namespace: media-server
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:pKNOk4WiCac4xSahfX8/uQMlZAeMm7wQP0m57Ih8iucwKk6uU6EhLswaHxs=,iv:p84onTmCgN+p0ZlgSAoNDO6Ro0IkKDoefefmGOvrobM=,tag:WT0tOkDBbU+jjIBhH4UVLw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:ECmWgmbUXK+5s5s=,iv:mCeCKMRtoxg8z8ictHkGp6hCKvCa769PYhAh9PMQFgc=,tag:VvQ7kyI0s54dRauhxQ7+vw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSVZjbnBYZTE1aFN0WVdq
        UkcxK0RBVThVSEk0eWhTblkwa2JHbDg5VUFzCmRCT1FpWE56QjZPVDl1V3dteVZa
        YTIxMG9YakZDb01uelFQQkJvY0dPb0UKLS0tIEQzVUJFdEIvaXIxOVlERnd3bFJ4
        cC9lOVE3ZUIzN3JJQWFtdlhEd295RU0Ku8enuhjOcmfKOSHgxpORA0Obvo5ZsA1p
        FzjIwLWQJtglIgaBYi/guRygUfbqj41xEmQh6rsk3K3p9hSRl1kGAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T18:54:12Z"
  mac: ENC[AES256_GCM,data:A5OPxV8iZw8AhYL1SYmJhNynPlI/fm5cwBXNRd4k97kmgqQ9L1ZdZ1ahWYxXwAaqofiK9vKM1mMEZsAtOUAoX7gWEQHXdxy2BHkaGDWLxHtUtIEF2bgx3C3KNWLQIkmeFJd3ZRPyyL1xeYDvOjoJoFtena9uI2ufcFOT0s4gNTk=,iv:aeC3njRFqXjYas1GV0gs347932QysPwBK9tRhPW8nyQ=,tag:mNfI4iW3lYgVp1XoSkKi7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
