apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: '1.12.0'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: longhorn
  releaseName: longhorn
  interval: 1h
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      orphanResourceAutoDeletion: "replica-data"
      defaultReplicaCount: 1
      concurrentAutomaticEngineUpgradePerNodeLimit: 3 # for upgrade of volume engine
    defaultBackupStore:
      backupTarget: "cifs://lin-nas-01.${DOMAIN}/Backups?cifsOptions=vers=3.1.1,seal,soft"
      backupTargetCredentialSecret: longhorn-cifs-secret
      pollInterval: 300
    ingress:
      enabled: true
      host: longhorn.${DOMAIN}
    metrics:
      serviceMonitor:
        enabled: true
  dependsOn:
    - name: envoy-gateway
      namespace: network
