---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./longhorn-production-v1.yaml
  - ./longhorn-encrypted-v1.yaml
  - ./secret-crypto.sops.yaml
  - ./recurringjobs.yaml
  - ./prometheusrule.yaml
  - ./httproute.yaml
  - ./secret-oidc.sops.yaml
  - ./securitypolicy.yaml
  - ./grafanadashboard.yaml
