---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-daily
spec:
  cron: "0 2 * * *"
  task: snapshot
  groups:
    - default
  retain: 7
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-nightly
spec:
  cron: "0 3 * * *"
  task: backup
  groups:
    - default
  retain: 14
  concurrency: 1
