apiVersion: v1
kind: Secret
metadata:
  name: longhorn-cifs-secret
type: Opaque
stringData:
  CIFS_USERNAME: ENC[AES256_GCM,data:btcjoFRgr90=,iv:OB9KI//dwipcrvY2NlJ4FwefixBuJGdjN4sxyQ+zCDM=,tag:UlJDTzkQalXoF0v30y0J3w==,type:str]
  CIFS_PASSWORD: ENC[AES256_GCM,data:NK0rHbUS4om1XZ4g+9KiM6BF5JlQMUA871ZtIVehpfA=,iv:BrASgK9LJHQHMAHGo0gWfU3GnmiSnuZgpExeXDGYMbk=,tag:8lNH+dqCQ3J0FU0q95ZEgQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q3ZraGJlTi9IeFJFdXFi
        dXFrWUlJQmwxNzhzMWJ2UW5qQWdlNFBkcFdnCkFFN3ZCYVArN2s1MTJPTUxkdFZi
        V2FqRlBKazNvOEU2bVZlUjU0MFB4V00KLS0tIGl2eVRCNzF0ZkliZTI5NlpjQTVj
        emNIZzR1THdQK0hHdml0dW1KYzdGTm8K9/IHGZ62QBGC+dkbcVvGcRj587KhvKjn
        AKnXdWl4SDLwVFbheTpiNm/PdyT1QYBaTdtjqAppXvKrN3dwhCyDQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T08:17:26Z"
  mac: ENC[AES256_GCM,data:loqrRlqpVI4Vfny8q0KdgGwgfxoHfSONVdnQvxqr2/5l7e35NX/wBXj4tHZONwfzPYi0kIpBQJ3SxNeEhol5/8McXsMUMjNkXC2lrUJ2LIA0BgcsZb5XoqwN5mnSMFdweCAyVQ2By/mx+I1DP+YpFql+N0boHcWcS5Pxy1r2T2E=,iv:TO5ObSwtZvB85YBywgpzJlhrmrF6hKrlOePBpEqmJys=,tag:KRusuhp7FIJY3lWeAcCEEg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
