apiVersion: v1
kind: Secret
metadata:
  name: longhorn-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ypY3XW17C3300DtSgVrFo0n86IWIxH4MfkMx9HRmkwm92QHqmcxvIGBFywfDKHeZbwb23LYe37LsDgc34F+qpQ==,iv:siNsw9FG/kiJDjGKTFSygrYosPQB07qUQ/kYhnYFo5k=,tag:EDKerzWo5RheoHulV4ehBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcFJocWF4Q29qUjdERFJ1
        bUFPTGxwK0Q2K3ZnbVlYYVgrOUVzdUoxbWk0Cm05QW5sRStUbUdyeU1xZnhVUlJK
        NllLZG5tQVdKRDdnTTFTb0dhaDhVd2sKLS0tIGYxR3pKUVF4WkZ2UWIyRysxVi9D
        T1N3VnJ4Y1dtZjlLK0g5NEdLS2owc1kKQBbduZeDkmRD5KHyFbbCEi6SjWMCKWBw
        Glh+GkAhI67egMr076rIBmGMPTVX00bfEOOd6FvTdHh33MeMG03A+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:38:25Z"
  mac: ENC[AES256_GCM,data:uXlkxFoSL0o7EKum+jZbPrNmnmp0md+3qqTANS3MRrcrEkI0IyAiddY06DO/+azb52neH/Doy3opI8qhhHaF45m/SN69aJ4rC3Qqvz7iSeUBOVOc9Y1iQO26il+n2vEQyYh0TUaidlbBPzxenMlXS5fVHV7+B/R2/tyMCbmV6pc=,iv:QHG9Vs0oBTre3+5kxNyo7YpUxDgbPG0g9wfmg9rywL8=,tag:fwg9mBYTNyYQxn+rhMBmYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
