apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
type: Opaque
stringData:
  CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:JyZia/3eZfUW7rMoy9u+q4IJ+Gk3BwtrFrLFBk2r/3P2Kg0V8uWCYvWTUclbBqE62E6IpLG9A0rgf9X6mJnZ5Q==,iv:4tNeBGZb55rb205IAVZTtI7KGUk7oar9ujKr5EusjJY=,tag:OhBGi49H6TTjz9UOeNSljQ==,type:str]
  CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:i8Ogfnpx,iv:fvoStWKEqhJN0lwvfQCfv8k/oe7lhA/2GLfPLN+/2Cc=,tag:OrNrQOMRSn+zZqspbCDZ4w==,type:str]
  CRYPTO_KEY_CIPHER: ENC[AES256_GCM,data:pquhlgIk3sIo27y7W+ZG,iv:QHDGr5QwEoGcuJJ+YYApNowquc2OedpcAHCiamnivjE=,tag:0nPDdKXsaWQc6TU+EQ7Rgw==,type:str]
  CRYPTO_KEY_HASH: ENC[AES256_GCM,data:hEoOnxyy,iv:LRGaJMXwxkmEIrrsWLfV2cepOBcf5Ew8iWjdvPe2noY=,tag:pyXaORN9BAetGc89mTNcOg==,type:str]
  CRYPTO_KEY_SIZE: ENC[AES256_GCM,data:Ij24,iv:xFCHDeSPzbetdnkRt4yxFPbRCIOvIScNEAde6Bq1GvA=,tag:Q2gZ/nqGtXGw+vx/8CZ/TQ==,type:str]
  CRYPTO_PBKDF: ENC[AES256_GCM,data:Zjq5GMPuBw==,iv:Cgub5XUwk9wW7VNxmnEK/KMSzYYqB+H0OhWfs2Pa0OA=,tag:36INSuAY2m4pgTJbjc858g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZzZDSDFwK0FUT1ZPQmdy
        dndKNTB6R2RzYndseVhxZHdpYktyenh1UmtNCkZWbnNpSExzbWt1emVTTWp3WXBZ
        MGFkWWpER3B5UVBuMm9rdVk3Q1hndGMKLS0tIDZTWmlhOGtkWXIvcTdPeHdoSk9M
        c25TZlZnUEVxSUhZR3pQYklDTnY0YUEKn7cErpj8RZxrgV5wzDjWHERiRKPMs7ti
        PAGdwc1dsI9suoB6+ZdG3NlquAkKdhOu1u3ocL4QHjxKZxvO91pJoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T09:15:12Z"
  mac: ENC[AES256_GCM,data:IzqzVXJ/ZLnO56HO4J7RyLFWj5/DNAZzlH8FmnPn1yiaWVE303BKC4SPjDspPaN9oxIx9UVIy4dx3lzV7VyIfZwuYb9Z62Bcq8neL3R0jD36pYyW20IujaLQYnmhRoUW9ll97w9/exJh9EW7te/BQ4zPeMnHQfa0zwr9MNkagGU=,iv:gme62OAD7hHJISL2EndZgo3+Veklx1kxmhGLgHJuPn0=,tag:oqSk0cpxgfZqmsd0t0zNGw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
