---
- Infrastructure:
    - Authentik:
        - abbr: AK
          href: https://authentik.${DOMAIN}
    - Flux:
        - abbr: FL
          href: https://fluxcd.io/flux/components/

- Externe:
    - GitOps:
        - abbr: GO
          href: https://github.com/Derlinn/home-prov
