---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Bazarr"
    gethomepage.dev/group: "Média"
    gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bazarr.svg"
    gethomepage.dev/href: "https://bazarr.${DOMAIN}"
    gethomepage.dev/widget.type: "bazarr"
    gethomepage.dev/widget.url: "http://bazarr.media-server.svc.cluster.local:6767"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"
  name: bazarr
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - bazarr.${DOMAIN}
  rules:
    - backendRefs:
        - name: bazarr
          namespace: media-server
          port: 6767
