apiVersion: v1
kind: Secret
metadata:
  name: bazarr-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:gT/gJ+Mb8QBTqfs0RBXBiitxQ8jX75iB3t5tZbpPBrovb+kCsZoHozW/LaMD3mfwEyrHYbBjw7GjN96aRuJ3CA==,iv:akYbbVPGLiJh/RYh/oYr1g0vWxLXr6eWXAufS2JfIpk=,tag:vzW2LN6T4KV/UaVLC6/Zlw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eEYyS1lPVUZScTd1SW1K
        a2NvZytETHJFU0lXSzB6SWZNdDV0SXNXT2hnCkt2Q3dRNkJ6bzYyRlp2dUNHTURq
        b1Znd0JMQjl3TDlZRDU3WFVGK3pQbDAKLS0tIHg3QlZ5U1Rnc09iMG12UjBRRXJD
        QmFCT0MvQk1jeGVEQ0dlQUVFUUVCN00KmOiQ6apyOMq/eM24XhYATwvyKB/ELBfP
        6axXOHeJ2c7QUhMIPYiQoA784/rti6reXyripa6Ctus2G181xqadsQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T18:30:03Z"
  mac: ENC[AES256_GCM,data:K2Pf43bol4n3aC9aJAsYGxdNfTYFit4gKv2EnV5TmHh7wUVv6gt3H/5KrR8WMhtueFwUc9eTE3uG6VjWN4rr81rFnlkUoAi8rER5WvFuNfeO9jNdYxpZSx+oWVg4HDBT34g//fxP3EHosDpuQfmme7oBiaTPTqn6RBpiuJxFNiU=,iv:lBIojoBJGVDjlC4FOwmENQVT9RjN4VT5ljOrwPUIqkY=,tag:5L/w6IPZIVEbomWAdj7Djg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
