---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./secret-oidc.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml

configMapGenerator:
  - name: gatus-config
    files:
      - ./config/config.yaml
  - name: gatus-alerting
    files:
      - ./config/alerting.yaml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled

generatorOptions:
  disableNameSuffixHash: true
