apiVersion: v1
kind: Secret
metadata:
  name: gatus-oidc
type: Opaque
stringData:
  GATUS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:x2B0myY=,iv:JauYmypqLIC7qbbAZnMcUE8PSHXwe/PvOr9D92r4ZVA=,tag:Oh+OCiezVEy6qMNgVRqeVQ==,type:str]
  GATUS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:KCqtF0a1yuAKtgxPUXDM5OBXXmQY051q21Qan+8MIrZOoCpvMnK/7F6DTl2E21zsKlE71gCuU3u++P9pBVr3KQ==,iv:QJ3EQFnb/xR/Vh9yX+oyOQ1IUInle0vBcX/5x8pqAro=,tag:VDQZ5UjPNfsj/Q6iAHPi7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSEs5a3lVeUFLSFFDSHpl
        aHBTMk42WUgvK1JyWTQ2aTg1U2pkR0ExNVZRCjZVRGp3L0VwYVpPRklpdDNNVUtJ
        dFIyMHJWZGxyNUNOMGRSOW5IRnd4T2MKLS0tIFVLcFBhbjJiK1VkUnZUckh2UnI1
        dWhGZStmY2ZPQnltNEtGUFJIbTVvK2sKNd3+l+QzsG/zNFrYeA3dWnxUH5auNbdW
        2yaQ8CW4An8SyhfY68dAVB0HmRHui5DsxKnquWlWTrdxvnhdeYak6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:20:34Z"
  mac: ENC[AES256_GCM,data:SWjBWzMQcpb5dmTkmnzmaCJxNiNvzHlvJV+PsbJ9fiCmw3w5YuvtG8ci5ZR4Vn4EQgQq6QyhbZiJ72rpEEooGTp5pC4gfu+muP7qfRi3PeSibZVB1X3p45JRnQTT0uj7wNXJy+DbTCTZw688e6L3YASJPkt1GHDgESXKMbGG6Qw=,iv:iSZQNbsDlMQYbbODcnui5htIrHp8nyt9BeQqgDU2kgk=,tag:pxe7cXlsVGKTBF1r0qcNQQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
