apiVersion: v1
kind: Secret
metadata:
  name: gatus-discord
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:0Qx1oLhJovoRy5qF+cB9UfV6InWeGwTvyhja//c46m8g1IuyuQWkRJDRiNG6iydtTUYuQj5hBzLsypfWBFY8xBPk0gzC2xK8ItIw8TT/HTMCy9DF7tPzke7S1ua1XCLUZOCRRDKrl6FhprNz/d8GhC2ORyrDZUIDPw==,iv:nuz/bx8DXux1T6wX7DKbZyz02dxFXCtcKBWeCy1x39Y=,tag:Gd8uUa7w9s0j+Qg7U+gUOw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdFQrcG96MTRDZzUzSFk0
        Ui8rTEtwK3lETkhUejFSVlpmZitPZU5CR0FvCnRQMTlrZW5hajR3UjAzRnhSS1lD
        aVkxckcwQVpPTzJBQjhFcFk2NGxKYjgKLS0tIHNKMWR4SStBeDBJY3pJdnVJZWxo
        TCs3YjJFcXhCSmRlU2ljTS9yQmhyanMKhcfzXt24nmyiJeYWzWpxlN9I3++K8XCw
        YNFu7IJDpl/CK2zDBwLiXgvk2BRriiq7Ewn/HTo54EGGHRN3sBnoMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T13:41:26Z"
  mac: ENC[AES256_GCM,data:jfPAIDKwmyatufy2PXlf7SJS8ddfWyKB9al9tan1ikBxhhCaaAe7HRUj6g0fuOcRgo8A2DTrpheKIjkAg+IU+qo58VVkScnMqhoUOEvFrawZSMZpmHG7E41r3RIkRgdAV+/gl9UoqAR87dzuQkbDQxXISRtSE5RVcXWhvUZvxAM=,iv:dhV/ipU92Dr1CEwtEtncuybClEKpVNdb4FLxPyz1H1g=,tag:cvbSh9FIgp8DPyQJoDUXdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
