---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nas-adm
spec:
  interval: 1m
  module: http_2xx
  prober:
    url: blackbox-exporter:9115
    path: /probe
  targets:
    staticConfig:
      static:
        - https://10.25.30.1:8001
      labels:
        host: lin-nas-01
