---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Radarr"
    gethomepage.dev/group: "Média"
    gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/radarr.svg"
    gethomepage.dev/href: "https://radarr.${DOMAIN}"
    gethomepage.dev/widget.type: "radarr"
    gethomepage.dev/widget.url: "http://radarr.media-server.svc.cluster.local:7878"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
  name: radarr
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - radarr.${DOMAIN}
  rules:
    - backendRefs:
        - name: radarr
          namespace: media-server
          port: 7878
