apiVersion: v1
kind: Secret
metadata:
  name: radarr-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:IMxyE+EMJqJCnpX5g/qD/2YcVE4FZf2j/e9jnxUDCdDoh2txj4FFTx1ODrUEnB1/oAcrged8uJCP0QbuKdbznw==,iv:GX7RTRpNkAvBVssa3ZPfKXhX1Tn9RVpguQspDqCx5Vg=,tag:Xvz9y0HSDf5fXOH9eBwvwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalFZSkE1TWMvTVpQTDMv
        Mm1FcVQ2K0pITFB1N3M2Yy84eUtHUG5hZTI0CmlBaG9IUUs0WkJGUDd4UjhCTGZn
        TTErWnR3NWliN0Zyb2ZObzBtSkxLZ1kKLS0tIFIzNHNodGEwc29OWE0xYmNQcUVm
        dFI2SFltaHRZVEl6NUd4M2k1LzVaNGcKX8tBcHazHahxJqKNgW2sG4hdaCL/vkQh
        R8LeGSlm4VwN3pvK4WjbGipF2o/yFpWrOIs95MEhE44Yu0r0EzKMNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T18:30:03Z"
  mac: ENC[AES256_GCM,data:NXiGIpjXymvl7o+xPO4z5a9SHFMxdbwbR8qEx182zDRGx3NXuSF2xbGEYub4ppqKiKfVo+4SP/xbTe2C3Y4wDzeNd92q9w8ZWoVFmhKNu0aAslDH9r6QA7rMDQ4woNNuXaHLYXgzvSa8C+UN+a5FELKDAkmEvZRRExll8ZnYd6M=,iv:VrCDK/helhbUK2WRmvMfIMQ1eOMrwWVWRQgEGD30/kQ=,tag:TWAQHbOMLjcjJsBDOkT03g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
