apiVersion: v1
kind: Secret
metadata:
  name: inp-calendar-rs-secret
type: Opaque
stringData:
  GRENOBLE_USERNAME: ENC[AES256_GCM,data:0NmZSVQ1HQ==,iv:KyWIp1VuEDuV37L83XWwV62518oES/k3zd8f4huNDrA=,tag:xxanoLJ49oxpf0oP7+QXEg==,type:str]
  GRENOBLE_PASSWORD: ENC[AES256_GCM,data:doCQ18jxRCQ+c4qdrZA=,iv:KI0/V0gxha4PP3nebNo95qGDqMLiwYCPG0x48s1RTRM=,tag:faen/h7vFaOqUrj/Vaqj2w==,type:str]
  CALENDAR_URL: ENC[AES256_GCM,data:hPsUf2gDIxLLY6tphl8NaZd/zZGhB6n0YXp9X+eg2aEq8kBndHcolMiw2bIPJeHHdLPttVcYBqye2qJl+dwfMACm79bt5uc8lntFJJkWh0NiTMMUP6X1+xlQFhNcrqLceJMDiXVHBvYDDFm1Hhe3gndcy5nKRwDsLQUy,iv:ITStZHTjNV/PPJshfcWJykovEkDs47M/jU661CyOy9Y=,tag:YS7Zz0ODy/S6z2HxhGwVZw==,type:str]
  TOKEN: ENC[AES256_GCM,data:CqS3ikGhthiqQt1/hurG0nDjpR7hxzZLyJrG0pMp82wd81JEETXDqjJlgwfpMUGgh9dW9d2xClHxoIY6dgRx51HVStXBIQkd,iv:WhtImKKFBnz+uVeyTudVixVRx7pIPIqGbI2UXZ4NHCY=,tag:QuYtKAyorPu5jfHwdlBEkA==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdVJyWDhVcTZrTy8yZzFs
        QUMwUStDOTRMRngwU3I2ZlNoSmdjWE9jUG1ZCm1malQxM3FTN1J6djRMYXEwRjlH
        RTUybnhaVG42WktZZU9UV0s3LzJOV0kKLS0tIEdPVHh6UDZuQ2RVZDgwbXpuR1E2
        QVlHM3lHcmgzWTVxcTJZUWQ4QjVEYzAKjtM1spAGQmPSc6fKQ98hq4mj28Rhs/Oa
        yk4EdV/rMRSQahV3tlHKxZaDJMKYxyjM1SsjU7pA2jFzYSJ4XJHZZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T18:23:12Z"
  mac: ENC[AES256_GCM,data:wxZsaP5+bcbEoOAJxZFuPNcK4NP/KWiVkvMX+zyiNxvenor3Twbtu7fAgJZv1T8TdsqQclxtpLLTwrUY0GXwRmyrEMDOdzTGtwXcsTJ8IeZeHS0RGXpwacNdIcUiRVHZsBRl6mENHtgHmFtlLfafvVGVWNh7fSMtI8PMYCgz9hY=,iv:YAptTavSLrdxxA8OMoJL0EUVCV742p/n7YY8IFwnhpc=,tag:ZgWetgtVEzS4MK/HMI8tIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
