---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  chart:
    spec:
      chart: app-template
      version: '3.7.3'
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media-server
  releaseName: sonarr
  interval: 1h
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: 4.0.19
            env:
              PUID: "1001"
              PGID: "1001"
              TZ: "Europe/Paris"
              HTTP_PROXY: "http://vpn-proxy.network.svc.cluster.local:8888"
              HTTPS_PROXY: "http://vpn-proxy.network.svc.cluster.local:8888"
              NO_PROXY: "localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,vpn-proxy.network.svc.cluster.local,${DOMAIN},.${DOMAIN}"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      main:
        controller: main
        ports:
          http:
            port: 8989

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn-production-v1
        accessMode: ReadWriteOnce
        size: 500Mi
        globalMounts:
          - path: /config
      data:
        existingClaim: media-server-nas-data
        globalMounts:
          - path: /data # montage complet pour hardlinks (downloads + media)

    defaultPodOptions:
      labels:
        vpn-proxy-client: "true"
        egress: vpn-only
