apiVersion: v1
kind: Secret
metadata:
  name: sonarr-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:llMCLKXcbJCzUQcQObPl54FcKCHC6Mi+XEbLTWrXfgpIBUp09yhZcIkS8FyIziQR2owR4KgY1JzUjwQpeOe2rw==,iv:APIPKG3b8CGARqWLNzbBgHiHCF80SoELz1W0W8APvyI=,tag:/MQeXrs9hH8ZUzDx6RBs5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOE9TVW12eXRqeWx5RHhQ
        Y2c0RUVLSnFZcTkzT0NKdjV1aXloUmNucFc0Ck93T01VV3RBdStrb1pUb0hscSsv
        ejRXSnllajcyNXd4WlhvQTc2VlVuV3cKLS0tIGxCQ2g3cEtKVmJWd1VkbVVvV3dy
        NlVKRDRBV3BSMXNFNS9OZTV3eUpNTGcK0AMD+7uAzezuc7tkn9MV/Efqt6VwnE3K
        guNa6161MpcZwJw+Ru2Uh14wafSV1NyTtrqFt4SUKM2QbZG0byCUSA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T18:30:03Z"
  mac: ENC[AES256_GCM,data:k0KQ57mQZPGEPRp4jCG2qfron43w1ZoyjZ7GzHSkcgkBShp3cxpV7cbbyaXpr0nImBAZGjCMhUYfm+Wt+XBZIJMFBx1o6XBjaaYufOF0nfaTPi8/tKvIFwkOPRqAlr+6BCiRUK2ZI95bnyCl9CgIe/xADt4nJZXN+kQO5BAERgc=,iv:QxaYQEgDbFwi8F0qY3WS8NwwZ6PmFWRxEp0gMvUGuqI=,tag:TOFzu5t5e2uSqR6VA+jzfA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
