apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-oidc
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:3/Hnsq8dmJiF9kAIs8zJaOKEfZ3lAQa9dTvuYSElEZz/gPGrZNY3d39RC4TKTEUyKRU12TM9WJM4k6NRzFc4Ow==,iv:vTjHF+GztRkOzy4fPVK1XCdYuOO7ha52Dr1QDEWAXsU=,tag:DMamcEGzgYY6w6YtrAEqtQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2F1eExsZWVxbVQrZmRW
        MjFzVnVYVG5ybTRxU253akI1S213MW42MzNvCnp6K0k0Q0lNYWFPNTVROXo3K0hK
        RlZOd3ZHNWFxeE42R21lYkZ1Tk9HRVEKLS0tIFVaOGNsTnFkelFFUTU0YWIrK09L
        dVNnbGcrcjB6MDVkNGhWaVhIbmpxa2sKZLPtEzB6LsFC+fYd6MJABJERaDba/3+l
        5EbsnpoL4dQgRBLGxZZIHnpxD4KFugAK3uf6c0qedyeYrtET1l7lng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-16T18:30:03Z"
  mac: ENC[AES256_GCM,data:+U+R5HExJtrS0zMjdojiGWwIo2SE/03Bi3U9FSk/dt5aS50aBYjXcZ2eXNyRacyK3OWwitFAP6PpzW9CsujrvpRZ6Skmr/+4CYymvLi5Kzyiqy/1QiNFdTO4LLe3hM30p0y8fr6N4TyNDhmM/YJv3d55FL5YqVbgYa4QB8eezsA=,iv:54+I6qpIak6C1hxwXckJevCAk5ZjnPefJ0z6pWZlpxc=,tag:9eMqbaXkOZJtsv8db76HCQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
