apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:fRlKwY/JlsqGQQeAa3kYTlq1ceW7p8PSXxB4vE2OvMpJ7FyhPNyAIEoGHpyg4/181LtgCCHBZUVZEuAaXE3y52hNh1hEW8kzQe6oGHwIJh3Bg53WrwJH/YK1fXf8lkliZu/Tei2tJGObkn6RuIpxIFsTT/Amb2inusaryOk20238l8x2QYjV6OM2F04/8HtFDLQZKn2jERZkOAUKBhHptgRCdDX+vD9d2D0w/A==,iv:jO+QFaXT9WLMVE8s0X/GjQbCv4LGZGxH/YO2XyrcYzo=,tag:Q87G6amZdSGQVUVjDlGNCw==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSG11L2M2RElnVnJSUFFC
        cE5qQTE4aG0zVnF2OXg4TXdvQlFQTjBLVmpVCmlKcHJ0clZjRHhXQi9aQi9mdG5a
        OG9RSHd2b3N6ZUU5R1lwTUttSkFMYmsKLS0tIHNRWkpmQjVaUlo2aFhoWjA1Q25k
        UHJyRytxbUQrZ2JUdjRDYUZKZnd6d0EKMBjudutIuL1VpPLm4cpMrWnTa62X7w/V
        pFbSPI994brXx6XWRnHKQAMSLSMygzLCARUMqVEWDWtVTcUcQDk8mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T18:16:18Z"
  mac: ENC[AES256_GCM,data:nPSSBZlH9nc09LVYwfpQkkII/4O3Y5SlvHoMCEKGeY67cwLLr8KuAwCpTSnRv69KKMNORpCpe/gnnXgY6svvHwwqP+m5bU8M8Jbx2huzWDC/wctcjjISZgfrGW6l/QFPauBYz+A+cTU3FA5Elmths1Et6MfP8lvSpmUqv/eqKeI=,iv:RU2AZ7B0WN39d9YnXvtPQ1iLOGMsDvy5aekbPE2kYik=,tag:JJ1LPdGIZMXFirxElCi50Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
