---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cilium.io/ciliumnetworkpolicy_v2.json
# Allow mktxp to reach Mikrotik RouterOS API (port 8728) on the MGMT network
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-mktxp-egress
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: observability
      app.kubernetes.io/name: mktxp
  egress:
    - toCIDR:
        - 10.25.200.0/24
      toPorts:
        - ports:
            - port: "8728"
              protocol: TCP
