apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
type: Opaque
stringData:
  address: ENC[AES256_GCM,data:NfEWGeSIAkV25SvEs4Uk8W5XKPGjdkv7wKT/6eDPHuiix80m56p+JOyEM/of6GSDL+seEPbf0omoyhxpI2XshGu6VykgE2K16/r8IiTM7bCbyi54uAls4bCtmZH2rUstEYCX+v0QFHSwuigvPzvBKTC2OoDG/ecIUQ==,iv:leXR57th+xE/amWKcV+/14PpdEKE4oXe8noWMJEH5aw=,tag:5EMp85Yw5dkBrJIYnAWRjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVG9DTGE4ODVyUEdyUHV4
        V25zeEcvbk5kc2VmTXBqWVVSZkxMWlhFSW1ZCnN1RFhjMzFVWG5NSjJBSEU3RzFi
        bnRMaE5UVkI0QUJQYWVRNFBETDBITVEKLS0tIDJJRnlZVzlJN1V6Sk0zOC9tSGhq
        MU8yM2lUemhhcm5mSjkzN3NxYlRBWnMK/sCgKcRjokD1uov6prQrpj8Hp+/CoPTs
        aj+oQ9L71LK1r81hgd3YxjOwP9ugdp2S76L4kHQTmQiqO2uOIjwXRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T10:20:07Z"
  mac: ENC[AES256_GCM,data:sT93Bpniiq+teVAq5Iy6uIBr6wcp9RB7wn9G3URqxidfiEIFofcjqwDZcH8PC3+wKx00hr3C8WAMgRSB3VSbv+skd0ITMRkKEHiarMsstQlkPEfRC6plCKZmS/77J4KRbtEEs87ozqN9Fh6dFTxEzfZ0qEBggOF9OFIkSGlYlhU=,iv:g7Cq6ZM/cpSndYfIAh/O49oEAhVZ8y2zBuY6M9bIoPE=,tag:xNeZw7lEBgtVcDi30x1z1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
