apiVersion: v1
kind: Secret
metadata:
  name: quarantine-oidc
  namespace: media-server
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:Q/nCElzZto3rdlNTOp8zFKZe8vfoGMjLI4Br/WKiCMZl4HYCNZqO0un0cQ==,iv:EzEtRLQ4bUmeYLKhczeOvP0492cBIJfLOZiLMpW4tOs=,tag:yuGZC8x9sfXGoSDNVge2nA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL0MrWm1pTUYrc3NaUU1H
        WFNFT2tJOEdUM2ZpdCtrZnpYQysxSDkvR3pjClREYVFSbzE5Z0NMMHBvZlZic2Jz
        dStpZlBod3RTUW9OVW1mNmFNSSt4MWcKLS0tIGRSQ3g4dHRKQmlkbEkvbHJuOURM
        WVhraHJyOGVrc0FybVpPVFZJNmFpNUkKpY9Jax5g3VAesuf23AK+jF+Xhs5K3THr
        F7L7vyuq/lBOemsvULklHq8LRJrdDWkIrbGuBE17WW0NanU4eyIYPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-15T18:56:10Z"
  mac: ENC[AES256_GCM,data:m0J4tMdR5tG7wLNUbwSLYobEG1Kzv41KRN+jmapkvAfQZX3mg7YT7A1wRVsOd/hWMDRgBtw6CfV+TBpsonM2W3jM08oLBiAsUT9Mz9ne/S+/c6xeRCMQLFeRvToNNu9dxvNMlGHp2bLh9pD0itU9117+FTazffovpKIwu51Dn1E=,iv:B5fRPp9ztjmkGeXrq/GvzFW/5+5Gd5I8zMPtKC0vkrY=,tag:8x0rQGz2ZAxtJC+Nv3ziiw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
