---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-nas-data
  namespace: media-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-server-nas-data
  resources:
    requests:
      storage: 2Ti
