---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml

configMapGenerator:
  - name: home-assistant-configuration
    files:
      - ./config/configuration.yaml
  - name: home-assistant-packages
    files:
      - ./config/packages/conso_prise_lin_socket_01.yaml
      - ./config/packages/discord.yaml
  - name: home-assistant-dashboards
    files:
      - ./config/dashboards/conso-prises.yaml

generatorOptions:
  disableNameSuffixHash: true
