# Mounted read-only on /config/secrets.yaml, which is where Home Assistant
# resolves the !secret tag from. Edit with:
#   sops kubernetes/apps/home-automation/home-assistant/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secrets
  namespace: home-automation
type: Opaque
stringData:
  secrets.yaml: ENC[AES256_GCM,data:2ZRj4UrIqpF3AEy0LsD9VwPcbCoJsBUc0I0gYvIX1MW+pHmPFt14SohmTUX7fLdj5H47dE9UV7PhbjA2CmGRKxvgf1BP9xFqnlPY2oCM6dAQpDham+4DWiBPgEBwvG6reCEopbjrEpVVqSx+oMwmh5d2go6pf3onXlSx4xmEU6ThkgU6TitTJbtUi8Y4gGkXkg==,iv:Jt4ESLXKj/bxmIobY9bOwWktsn6GBRyyh7+mWQMNrr4=,tag:DzGKj/KJ5Rzb1EOnfM5wCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSzhEUXJSRnlPL0tyS0py
        V3R0Tit4dk9HR2dkVDdnK2tzUmlSNnd0RW1BCnBFSE9tamNySW1sYmcxSUc1OHZt
        eDlaSm53ejgrb2tkY3l3MERGeTA2eTQKLS0tIHAzT29KcStXWThpeGtPU3p4Qmx3
        VUFRQ2FUamhsakkxWllDVjBDY2xNZ2MKms6Gh8z0TPNMqPnzd5EPmTM+IUzSMCvD
        5o2xvg2bCSFETecz5tuGnZ7eGFOcF9M4KPGsX9BfsHv8mU0tqUvUjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-11T12:15:42Z"
  mac: ENC[AES256_GCM,data:zj3E8dhmhCOgtA0gPStDSVVx6vKYPwZwwUkcImFcICoB0+NB/Qt78rRBNicbrA2bxc/Bvp5l01DTP6ICZdSe9JR+0bT0hyCTNgq1UTOzur/RuRxFbyTBiArn6rt46+S8dh5okAZwPYSRHb/Gy/7nSX3BvMC2mVga880lhdw7vvo=,iv:+n5z1aBEytOmVD2P6RwgXldbU6NWrll+P55eXytI5oE=,tag:9gq1uJJlExeOUwaYuVCXiA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
