---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - maigret-pvc.yaml
  - maigret-deployment.yaml
  - maigret-service.yaml
  - maigret-httproute.yaml
  - cli-pvc.yaml
  - cli-deployment.yaml
