apiVersion: v1
kind: Secret
metadata:
  name: maigret-oidc
  namespace: default
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:KWxW5Eccw8OV2fNiQ7BOVfV1at9Ii0KrUTRabsRx1shzvnQ/FMN+BPDWBA3jH9CQhIst7mAt9DRTMZo035HVWA==,iv:CtxOEqHryHHhFTlrsvAs218X9UwJ4m9+43n4cZXfduI=,tag:G/AtX49aYaOOcOWPWd7/tQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDZVZTU5SFVGTkg4RkRp
        TklMQkhvcjhoNStuY056cFliOS9ONDVWcGtnCmR2eDQ2SWdBZy84MHJxSFNOSTJ5
        eGh5aEJJQUVablFhK015MkhrQ1B3cU0KLS0tIFQxOEZVbTNsZXc2RUJDb1JFRDFo
        RVZ1WWNmUElxYVAwbGNWT1VLYjFFRk0KUed5zKjX1wUnmF+8Lm1ePdBvCyJd6tF8
        mjHkW/GqKRe7MjcACYWng+PpzkRGwfhVtITUKP9Mz+99Pt1nfuHHbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:38:25Z"
  mac: ENC[AES256_GCM,data:GdKmdOh43VVljW7V7wo/aKCWevI9MPMbfMRXM90EkR4WEWfEEszo6m/7QSMg9rspRiriz3+gHkMSuHT0r3L3SD4LWCu5ozE1UgozQTvB/KNiIh2BzGzIK24GXJixdlbOjc7xTz/m0KClKs1zj3wejWwNdTQTUPynDmWPfueT+ng=,iv:l9l1O07T01Vwb6HRlTD9eOAL5ZufjQRh4MuUxflrvfI=,tag:sbQ5Twj0czMquSlNgNSh1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: social-analyzer-oidc
  namespace: default
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:yGp12lLk2y6MsuMX41Htwv7EMOO8dZgDD7pgkghZZWyqCxKTu+4tVQaOb9VqSXuHfbKnc/xuK/qWJWeGEby2VQ==,iv:RKkQ2v4gVJmP2ADZsZsRyaLJC2S0Dy0P/5Sm6posMDg=,tag:r9Nf/O8DzBZN05L8ciS4sQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDZVZTU5SFVGTkg4RkRp
        TklMQkhvcjhoNStuY056cFliOS9ONDVWcGtnCmR2eDQ2SWdBZy84MHJxSFNOSTJ5
        eGh5aEJJQUVablFhK015MkhrQ1B3cU0KLS0tIFQxOEZVbTNsZXc2RUJDb1JFRDFo
        RVZ1WWNmUElxYVAwbGNWT1VLYjFFRk0KUed5zKjX1wUnmF+8Lm1ePdBvCyJd6tF8
        mjHkW/GqKRe7MjcACYWng+PpzkRGwfhVtITUKP9Mz+99Pt1nfuHHbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:38:25Z"
  mac: ENC[AES256_GCM,data:GdKmdOh43VVljW7V7wo/aKCWevI9MPMbfMRXM90EkR4WEWfEEszo6m/7QSMg9rspRiriz3+gHkMSuHT0r3L3SD4LWCu5ozE1UgozQTvB/KNiIh2BzGzIK24GXJixdlbOjc7xTz/m0KClKs1zj3wejWwNdTQTUPynDmWPfueT+ng=,iv:l9l1O07T01Vwb6HRlTD9eOAL5ZufjQRh4MuUxflrvfI=,tag:sbQ5Twj0czMquSlNgNSh1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
