---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-analyzer-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-production-v1
  resources:
    requests:
      storage: 3Gi
