---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: social-analyzer
spec:
  hostnames:
    - social-analyzer.${DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /app.html
      backendRefs:
        - name: social-analyzer
          port: 80
    - backendRefs:
        - name: social-analyzer
          port: 80
