---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml-server
  template:
    metadata:
      labels:
        app: plantuml-server
    spec:
      containers:
        - name: plantuml-server
          image: plantuml/plantuml-server:v1.2026.8
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
