---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-system
  - flux-system
  - authentik
  - observability
  - cert-manager
  - network
  - vpn
  - default
  - inp-calendar-bot
  - longhorn-system
  - vaultwarden
  - system-upgrade
  - kube-green
  - media-server
  - devtools
  - home-automation
