# TODO: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: unpackerr-credentials
  namespace: media-server
type: Opaque
stringData:
  UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:zqaLA8ipzEdLqe+QX93dtt5Qwelu1WfvfzfM+ka31cY=,iv:SOlCB7owt/x5xy8X5FAllTLraMe6rjfz5q5oYGIV9Mo=,tag:EbDJm375rJHBgv0nh/zbVw==,type:str]
  UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:nE6UxlvM1P/QR5GuEeLZBeX16I/3LWfZbuYIPnsc4eI=,iv:lSCCwt61i+0sQYyXbo7SRtjd9ZWQDmNsIlMCKt1Tjtc=,tag:Im1jqNXgvsoBYY4VH3/I8g==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2h0ZjRjNlRWSzg5SFpq
        bkY2cTNock95ZGJibUhKS1dGU3lYR0JVa2tZCjNGMGFWQXA2U05OZ0pscXkyQnJR
        d3ozYTlyTXVOYStoMkRkejlodVpUbG8KLS0tIGU3eWwycXRESTIrWEgzZnZ0WjJ3
        NVlSYWE1K2MyVHlvc3Ardit4ZzR1eVUKeyWNjiGwyFN/S+boIw8o8akU8kuPShhL
        gjxblVULVULmOcNb18v6ZtunZ34wAlTtwz7GbUZAhYKnW1gRjgu+gA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T18:54:12Z"
  mac: ENC[AES256_GCM,data:+R3dG/ICWRZkqM5Eb+SItrtVV/FjXNsSHxPnzkkh2Wj0ybDf4vSqLGtHKj4AZnBIX2wcldu70vVaGiGtB86Cv0fen9xiU1r3DTOW5F4pVDiMxhDpWQTqAKYRVPKX/tBiOvVRJqwHvTTIju0I58ndb0dJ13UE0h8awXLTtYMKcmQ=,iv:KO7p0Iirj5b8+oPDGm/oZj6vI1LIMgwJiMBr479VLBk=,tag:45d6cb1VnI3EfFvzk0/l2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
