apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_AUTH_SECRET: ENC[AES256_GCM,data:avePXd2Z0i6izV6WHXMDx3UO+7Vno4I1q9XY+PkbBt63Tpt9SgdDq5X7IegO3xfmj0ujTABcKC4pv77epVd2dA==,iv:a5YoqFKxieKIAHBL+i1SYlCLgsEHJDH62ofUfDTNcJI=,tag:vgZHyqSaj4SeBQ6vqpzkZQ==,type:str]
  HOMEPAGE_OIDC_CLIENT_ID: ENC[AES256_GCM,data:sSWrv057yb8=,iv:EHTXwvc+UZofhFdsrpMFog1rN3hp3KwcAob68xhJIfs=,tag:aWcm5nARvH1Ow5YmhWJUoA==,type:str]
  HOMEPAGE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:gUXiOe0/oQiopAgbQCutfTj2/2u7DVyo6NgCCRTG4sfOwk08GdI2nRxw84uobFFzwZSu9MjA/ek/v1coTcDw0g==,iv:WI+Le7Us+h7k8mhM23QecrT3CFMUjrseV5igKMlyXb4=,tag:aDWIRYZMOtZOp9YpazLoLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdUVjdmQ4V3JxWHAzYUYx
        TkJlcm1rZVBDbUhPdTlTa0wwWkR4c201VlVjCkNac0dIaC9nZlpESGc3alo3Z0x6
        NTkvdjZEMUlYZTM4d3YrcnI2ckVXNm8KLS0tIEJQOUE5dUtaNkNQL0FrYnRycXQr
        OEJWUDF3M2txVnZkMGFXTnppdWJpTDQKg0XHtD4gI3LcdmEa8QdtZseCzGBurmno
        tSYhEEVWSLlRta1ODdp2jz30L5zegpuS33xUjE4zowm/ZFC2hZ3fKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:59:27Z"
  mac: ENC[AES256_GCM,data:Dd9knfMxibW0BITpEV+yyYtMHNlYCATWNc1QDjn50OOLzdabQR+PPSnjvprPIdiEb9WI3SZzLGFECcvlw5JfUEGkc4ldGk0z+/LfsWdpAg6eH9DGsRFfxe9e5C29NRzVp3vr9P2ldPdJZbNL0sjsk0xSzSUC+6tAGKYYUuTjIMY=,iv:fBxxfJd59TUz/hIoFxQFHJSvFKPF2UnSnvHZKBmfgEc=,tag:RJ1AhqlIAlyA81AFVb5ENg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: homepage-vars
  namespace: default
type: Opaque
stringData:
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:A23/C4ZVaWkDVsSJsDgGASPnaRgC4OTwKW9NPAvm7kA=,iv:AelahiiWg9w0bYr2zoRHKzEUPNg9HRi+aTw0EYKMTbM=,tag:OQecmFicUswOWDZUAUVpCA==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:7yTzpWUZXCG9HOuPn1I5rxALjAgVB7DvhNw0VcbPiN0=,iv:gbQg4Xahhz67hRROCyKSZ14AXmHz4oOYGfqOUbQ0yWo=,tag:zx5HmMllPFPzgAh0xctGWQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:S4ZqidxNSoeSafDi5ry236VFOOOgvQCGUROAKiHmFuM=,iv:tWdpj0B8FPifg1CLrtms2qpJwRnDPk6zxZvJupVRoV4=,tag:2NPkjnWA6zHS6Lf1ia1OYw==,type:str]
  HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:tJsIZjV6cxHiOUBkj2vuP3IoTFi9SgOwGMMGheKclUw=,iv:QfnSy0Mw0LHlPUyqMKDng0jBCp+K/CSLpCkDnh2qtiM=,tag:2tqGtRoR88dXo1UW5SrbIw==,type:str]
  HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:S04eKid9xlpq6lKYEVHBUQdxRg66bpuncw==,iv:GQGMsDKmAo9bkGWZqsRp/Q71WtbxUd3yXa0TIFAe/Uw=,tag:TaRNRNFAZvUTxUh9XFgaYw==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN: ENC[AES256_GCM,data:rZEPjl4ZH8v+T2lMgLEGmMGUxWpjs9r4XiNk1Hqxrfs6IV1V,iv:jAVku8Y8r+btJVCwJ4oBKkO47SiDY5fjwHe2oITfUnw=,tag:httNbg+2T2TAOjjebny1xA==,type:str]
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:iqMe5eMCi1ySATVkyRKeobqHLhQNA/Dgq/oaRDSgGkI=,iv:WvFcsDo9mEkUdHW1afkt/aI+9ehc4fNtxkYOIASSJFU=,tag:sVdn8PAiu5u0Y8b+JDxa9w==,type:str]
  HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:wQ+tUCA=,iv:+xJHKvxj5oTtPtGTkLYBW9ihdWyX+WS0hdnrBJw5Pe4=,tag:g65DQuV7hAq6pQIYd7Rneg==,type:str]
  HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:DKNv19bxapLnyFPA4LpKxvHQ7WE=,iv:RcE8Y+isRR1HrvUCfdSMaKcgk++5IPY8uUNo3VmZgB4=,tag:7uRSfAgc2Dzh5FIEzVJ+oQ==,type:str]
  HOMEPAGE_VAR_GRAFANA_USER: ENC[AES256_GCM,data:68dMJMMNFkw=,iv:jfeIL6BBlOMBFzFylkziFvqR6WvzYPItzTfc2megyGY=,tag:I5uw50hynuEdLYY++sjn4Q==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASS: ENC[AES256_GCM,data:FXrcZuLl7AlkpZYHNrIeokp68pk=,iv:+0OcRomYsrAPKILow5oXVuhGXkqCJTG2HM7XN3qSguc=,tag:SjaBVb4uOSMl5ETezZSw6g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdUVjdmQ4V3JxWHAzYUYx
        TkJlcm1rZVBDbUhPdTlTa0wwWkR4c201VlVjCkNac0dIaC9nZlpESGc3alo3Z0x6
        NTkvdjZEMUlYZTM4d3YrcnI2ckVXNm8KLS0tIEJQOUE5dUtaNkNQL0FrYnRycXQr
        OEJWUDF3M2txVnZkMGFXTnppdWJpTDQKg0XHtD4gI3LcdmEa8QdtZseCzGBurmno
        tSYhEEVWSLlRta1ODdp2jz30L5zegpuS33xUjE4zowm/ZFC2hZ3fKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T19:59:27Z"
  mac: ENC[AES256_GCM,data:Dd9knfMxibW0BITpEV+yyYtMHNlYCATWNc1QDjn50OOLzdabQR+PPSnjvprPIdiEb9WI3SZzLGFECcvlw5JfUEGkc4ldGk0z+/LfsWdpAg6eH9DGsRFfxe9e5C29NRzVp3vr9P2ldPdJZbNL0sjsk0xSzSUC+6tAGKYYUuTjIMY=,iv:fBxxfJd59TUz/hIoFxQFHJSvFKPF2UnSnvHZKBmfgEc=,tag:RJ1AhqlIAlyA81AFVb5ENg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
