apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-sso
type: Opaque
stringData:
  SSO_CLIENT_ID: ENC[AES256_GCM,data:MuIA0IR0zA+fBnA=,iv:bohxYmokGOGGLyZRNbQIuOlWd6T+/XqO8ArnG7yP2XI=,tag:zdb12nPIffjzHQZfVm97iQ==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:tEKxD7MzANS65lnNCibaljPK8vF22dZGk9OOyYNboLBb2ntlxVEfns3cfXBPi0i2DC2bp5TDKflGohZm0rPJew==,iv:rSUNgbo1dy8BbL7ZrphafZGFgrf/s4PWZ8rIjK60sjY=,tag:YJ68hBEzJU3aZ4pLgC9qwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SjNPQ0ZyTUE2TFpqS3k4
        dnNCS0FlNG0wdG9paXNsY1ZGTHhUM3R4dVNrCkU5ZndPMXpOM1lyMnRaK204ZUR1
        WUJhb0N0cmhjcWlZNC9jTVd6MmlNT1EKLS0tIHprZVQyblEvUVhIbS9TSVdwSHlU
        Rk5jazc1eGtPcjVnWHF6S0IxTFQrWDgKlOw4K317vETQ85mSONjC9iajfNL9/RAy
        LYkDmMz1NX55vHFfTro8OtfZsGLOax385r9hniEu4eYzQZ6W55ZDqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T15:30:42Z"
  mac: ENC[AES256_GCM,data:Saw2NgousFBvTom7umGeda6EnTPhtCGYFQGcSdrRpQnKLROJfQPakoiMQNCu4jSWGV8Zt2s8dCMOsikgZeUhqPEXfrml5Z7u9x8p71ySIJrYajVZpsN2NGayOhnUlRxYT/kLZeultBS/OvVQXY7wDBTuVNSV3dwcIR7sHd9IuJY=,iv:bK4O+cbC1y6vqz3DY+kowqzRJbwkTIjGB/a/pFEuYkY=,tag:rbYCXe+YYpgC7tRGTcSZDA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
