# TODO: sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
type: Opaque
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:qa96hIaMskR599yiZjJhaVvzzABya0Iulr2pJjW2Hibmak6MerrWU7gcnxJxu7dYfh8ovf8HEFg82rcrizcpKfU902HT6KtbJNOuFMRAaVgr3pzX/Bwz90yG4KGJakoaR0yh/k0yjJHNK+CtuuB4WwsOuqfjdg==,iv:amCh5rd/85ao5OrS5ToXzLvmP2EYyLtrUkE2gDV3S0o=,tag:/bJAq9X7xKGPDSyHPg5RSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc1NFRVBseHJQS2RaQUFW
        NmhtVGFJMFdMbHlLNjIvRTBnYWltbWJSOW1JCmlZd0ZhMWtZWjJDdXZJdy9MWEsz
        QXFsbFBxY0gvcGFqQ3ByS3RYNEdoLzAKLS0tIFBrRHdYNk1PNUwwUWJ2ODZPQmo1
        K1IxNnVxZmZlWEkzVkZ6aE1oc1VlKzAKjQJgcNkBwviACwpsmvosjo2Tp4Q3Ty/T
        cJyJo+0fuQLTCAN8PIk96n05q1tQeyCrPLm0uw+f1hjEpKWWCQyKiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T14:00:06Z"
  mac: ENC[AES256_GCM,data:nUTFuFEJ/q/zOvnwr4hxDab2w33/5Vx0pWaAI6Q6IiipPqYj20ovKifQOAIIO/22mqZnxm7ctad88L9QmI9vTrMCjiHrsqJu2Ds9vh4BdLX+xCGZaZOp8QoKCWx0unUZcrow6IDTZHzS18upwIgmnzLyV78N+far0/C5ZYaXDes=,iv:+9xpBaAveR2ewOUjkGle7nOUBayh4CVy3vQxjXFlQ2A=,tag:/o0rsnKYH9Kp9W2It4hTiQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
