apiVersion: v1
kind: Secret
metadata:
  name: inp-calendar-bot-secret
  namespace: default
type: Opaque
stringData: ENC[AES256_GCM,data:B99CTPTz1WgzDwxcpjeOvLBxKDMde8aZ+CtRyOW3/O+kcCYOuBMndLgeUuetLzba7FR1pZBrsDDtZ5MD+qjhqGzPQYJQU/3/gRXOHvyO2Z+uBcdyvevvXMB8/KuzAOlb7hpJvAD2vbgkh+KS6ro9nf+qv697t54MLwvTbCJUyOXmR+6d72JIE03z3IElhsksVfFIXDP0uNUcExCyHb8eMAUDO3WMnM1mLoHTKXG7ky2mEAMBcUXUIpP+Jqbz7ak8NumEKcwlNltF54LassbDAb6VvMnzd805kz+YuTESvT2KOdVPgDoQL8DwSfL4Rpe/t1QTulDP6vDlSstbnJMVVOfLcAb/6mzMfRd+QbHeTwZ7RoZ2yXBfqWG2,iv:m15YHoMnLYGfBkau7L9XvU3TuINTdBSjpWdxqIwxl3w=,tag:HVFD9ac3EI43oiNd2JTc+Q==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByS0lWc0hYc3VzK1NORVpC
        YnE0Uk9DbTZLMURpNS9tK2tVSmxQMkhLRjNBCittYWt0eGJ1QmpTRGZBYnpTTkJt
        MEZWS1JCM1NUWkhvRU1IM3dLM0hZdG8KLS0tIFRXV2xSaExjRWNjbmg1QzB2c0dS
        MHJ5dnhnQ01Tb2ZWUTVvaDFkT3A1OWsKv5nUbRKhW5+gX1sSx4nO0unv0bIwzlTx
        xfd6kzwGubu9HO0dUJyVDoztQkv2Y6ydgCSsVXG8enZ2GNprjAAH0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T18:04:54Z"
  mac: ENC[AES256_GCM,data:CTPHUs1FZM46eyNlbFYmwkhUBhNsQUvWaGHhweEgjB6X51rpk57VMB/LQnpueQVIybGNn5CxFaOb0E/MVCcekNloHOne52E0IMUSqbJjmE2gfa27olL7sJY++3LpY/X2/fhfYlHrHzJw2kNUPjsOhEbF05BEeVmClGilJCN2Cak=,iv:5iFIjO/iRk6uHFEmkeFxPBN9infh55WZYBFt2MjxRTw=,tag:Eh/3cfGsLIlalg2bYnXTfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
