apiVersion: v1
kind: Secret
metadata:
  name: netbox-glpi-sync
  namespace: default
type: Opaque
stringData:
  NETBOX_URL: ENC[AES256_GCM,data:DRZrgpDIaJPsOIRSlZ062ApzDSTmFVIZkHnn/5WDKicZfzogW/i5,iv:SOBsJMz/p8RDdZJv23Bhy5stsvKdduKDWMLfFkZq4k0=,tag:VRuNhB4M0/9FbhBXM4CvZg==,type:str]
  NETBOX_TOKEN: ENC[AES256_GCM,data:6X8BUruEsnXYKCZF/fFhV1DiN3C8kvHN3Wo27oOGOXprLvkQv6mab6L+cynk9oSG+r3+stk39uFk,iv:VfbuDexQ+XHSGHny3JWchK2Z5ckbkPcMnjp/drjkonk=,tag:8oDTgQG+cL1KOH+EJOVChg==,type:str]
  GLPI_URL: ENC[AES256_GCM,data:QWXiEcqi3dDWdoG8M8kqUmnsKUDP/pF/n3KEYtD+1Kgxd8v6gKTS+UH1MzeV+FcikHU=,iv:blx9QVzRJAD/Umxl4AYZy9NqkSRLRNFoFek3QFs7A0A=,tag:foDNmVbAUa0FfNV3TUouzw==,type:str]
  GLPI_APP_TOKEN: ENC[AES256_GCM,data:Y8slwQ63Bk7k1Y6rA/AUWom3ll2MlUTbvvhXfOGhuxlcoGVfyVQY3A==,iv:fpVCJ2oR2KMkSDFWcYYAHmRQwTFBiKN4xND+iInevvw=,tag:FRpkGMK2w5AysZDf1VbRjg==,type:str]
  GLPI_USER_TOKEN: ENC[AES256_GCM,data:/yxhUcv7fGv/zRsiOH6V2Ee2pgqivn0YK/GRIvcXsWpDIv8MveJVcw==,iv:T1qevVVCxinp3/zTRkzYBnL8EaPQomB08+uG4usS+/w=,tag:/dgID0LYCEkzlNoeIc3lFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQWthbVlsWWJxc0hUQXNh
        MkYvTVM0YStxYUdmSEpMNnhLY3RCN0krT21vCnY1a2RkaHFrTHdCUlNOdEltRGpr
        S3lTU0wvV3lJbWIwZ3RmMEQ5Y2ZVYmcKLS0tIGo2ZzExL3ArcXE1cGxWVmkyQ1By
        a255dkd3QlBiZXFqUGIvYkM1UFNCYkEK/Z7hS7Mn1kryPnuEvBaWNWcAEsFj82bF
        57mU3LGQ8Wq/fIhcnMKLEQO9drpK6FoM3Bi5kfDvJiI4maVhtu8WVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-12T19:08:31Z"
  mac: ENC[AES256_GCM,data:yVm0GfI3XertP9BZ2+Ui6jZRhcUtTq1jUBwZv+Y/butK23n0aEQuMoPAt7QgJ3j7dxcb9CDf4AgooRNk0lkLOjV6C+nC85vYEk/DM7gY2w44GlLp8n9ZIzt91c0swLHn0Aq96Q/BvYHmN/qyAgVwG+ZnuqikymF4zlXqR5TG70c=,iv:Wm5xu/XsLH0X/0QxHlpkoShtgUSIB0hBGIeO3CGCmZ4=,tag:GdkDqSg0nrvNFJn4Qqp9jQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
