# Créer dans Authentik UI :
#   - Provider OAuth2/OpenID Connect, redirect URI :
#     https://gitlab.linderis.fr/users/auth/openid_connect/callback
#   - Application avec le slug "gitlab"
# Le fichier est chiffré mais identifier/secret sont encore des placeholders :
# l'OIDC GitLab ne fonctionnera pas tant qu'ils ne sont pas remplis via :
#   sops edit authentik-oidc-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-authentik-oidc
type: Opaque
stringData:
  provider: ENC[AES256_GCM,data:Swjb4q6owky5QHNOULReVan3ajVQ2pBrTcG2y29U2LA8x2hDkm/VbUwM+lmVOkCUgKPy+nQv/MU8XyNytOeIWpVPkIsZ+AGl5wbBoPct19XE6nwlNl9uvDK6MnYcmZFrj33ky8XMacDE3v8x6gmyXJ1jBdvZGwNZ+AM5d+iunK6yRndXTbv0RnunwD0He0WfvYJKaJu7VuzsaHsbOM1D8XzPq/n31aJS4be5swaOcV28VGY+DIzAtOhxLVp+51Xg2jxb3ZMFYJQ0SC+gFz7Y7OGR7KCyp5AMSgzhizXoaxkEJbJ1zrxZxC8vcfoBDj0Wmr2ExYP9zuQjXNnU33Bj+i6glLL6KyvjW328KRKGdtbkAkFKsh0YLxyrNtQEU0iqQ5Aj5WK9qfZSgGiUHnpAr+Pv0CUXhmpo8jj31huUGByVLM3kTOMTXqnN+cc4YWWv2H9C45e+s/qPaaAN0qZv6wnuNrXKS7pvSzm/Q4JSWDkLj+A/ZOofgHFGGsSKxiJXS0FHbdZnGp4iuMu2cEYIjbJRhqUS/o4JMECDC9JBt0lPyY/deB+8URFtahxm8chsSyBE9D5bbq8KVy2NoKMIY8Z98w1cHETWqdVeErChXd8/FL3P0vi0T8w48ok=,iv:NxA4JHLqW9KIzM4OpCcQXOsb0V7PHli37l/p9ANWk9Y=,tag:x4k121vygPZSMo7f0z+FLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUGg5b3ZjRFRQYzJqbFRa
        Vmk4L21yVWlxQmtUa1lwY3ppZGJLY0lNREhnCmNaT05uTEs4NEozOFlOMmxyS0VJ
        enNBRmRSWHNGMkZheUxzRWt6RzZTZHcKLS0tIFNpK2VnbzU4ZlRNcGlaSExta2pF
        T0ZicjBLMVN4K1ZpeFVQMkVzaXVrbEUKRYNSuxeQgJcAqMOxYFuTtqVMOIAr4rJB
        5wT7vKm9rDwaAGGCuVWK6TAsos7nw0PbCdYG4QUb2i7wnk8BR073fQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-06T11:37:44Z"
  mac: ENC[AES256_GCM,data:TlPUgPloIIr7w4uaJFUMm1D2xnRxUt1hPOQxF7tS8TeVMT62URtk54XBAJaCXWTVP+5FkntZtXzgi5MO57l5s48/DHPmH9h6TLhXNnuZTecaMfZOHX3tQhj3oKdSd4cTh4t5x9G70niBEZIWUzrDq6kqwytjXRpLDHt2fJzQbrM=,iv:FPGpVVlo2s3AXoKB4Vge1mbvgp20YYWAQfu0srEOIOM=,tag:dgGlmiHKS1KG4YWYyLeCxA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
