# Generate the password, then encrypt:
#   openssl rand -base64 16 | tr -d '\n'
#   sops --encrypt --in-place secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-initial-root-password
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:qFi9S2iq/ZWh0nUyVanX/AtyXkek4nWk,iv:1MleEhw7iPcJyjBPNIuGGrL3aoCU+jHl0WcvhGobYhM=,tag:jRuDzQFckek4JGrqpi6+1g==,type:str]
sops:
  age:
    - recipient: age1sdspueq7sx87ahpu2aqsg5xfypn0qmnadt67qpatahja8e7gap6qw55hq4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ2ZTNGE5RjFTZG5uMGhX
        clJlTGpLeWpvMmd0Q21tN3h2bDZ5N0FJempjCjZlU3ZCZVZKOTlicTdxKzUvNzRG
        aVNONmh4NU5qR2c3UmVLYy90RDdRUE0KLS0tIG1UQVQzbGNPbjBYRDFPUm1aV3pq
        dVR3UzB5eXFLT0hIYWI4ak5HNlFoMWsKnRH8+mD/7rkT7jctMRslhxkk/2Iw7FDZ
        iwf6UfR1c0zQn+aQbDdph/KVWJFTtx7ENml5uzUrsclT+/7Hd4LuBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-08T11:51:56Z"
  mac: ENC[AES256_GCM,data:DUSG39at0YdqyUTEqwTlwW3RI6B+pY7K79MAYWhfjwYuMtYWenlmo+iB9T/OeyxvJ+GmENAWOaDgttFNYc6DcLzMvpCExtE6fY1b/RRwRUwPJUIOJ8m9eLBDwQ2iJzItaf7ui3p/ihppNhuHfZmGCfzdDC5wpiJuN+P0fYXeH9s=,iv:fo3L5vQgzzOd15ucqHTiaJWSKr5ORGj+jBzR4vA0HyY=,tag:tqgZEDAs8OAMb0IHZifghg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
